- net/asterisk-1.8.x/Makefile
- net/asterisk-13.x/Makefile
Small Changes to the Subpackage Description in Asterisk-13.x and Asterisk-1.8.x after these changes were already accepted in Asterisk-11.x
> Small Changes to the Subpackage Descriptions

- net/kamailio-4.x/Makefile
> kamailio-4.x: version 4.2.4 released

- net/freeswitch/Makefile
- net/freeswitch/patches/libs-apr-configure_ac.patch
- net/freeswitch/patches/libs-apr-util-configure_ac.patch
Signed-off-by: Bluemax <bluemax@users.noreply.github.com>
> FreeSWITCH: fixed cross-compile errors

- net/asterisk-13.x/Makefile
Add the missing soundfiles in English...
Signed-off-by: Sven Pietack redfox1977@users.noreply.github.com
> Asterisk13.x: Add missing soundfiles

- net/chan-sccp-b/Makefile
- net/chan-sccp-b/files/extconfig.conf.sccp_sample
- net/chan-sccp-b/files/res_config_sqlite3.conf.sccp_sample
- net/chan-sccp-b/files/sccp.conf
- net/chan-sccp-b/files/sccp.conf.realtime_sample
- net/chan-sccp-b/files/sccp_sqlite3.sql
- Update revision to point to stable V4.2 release
- Add sqlite3 realtime example files
> chan-sccp-b: stable release / realtime examples

- net/asterisk-11.x/Makefile
- net/asterisk-11.x/src-lantiq/channels/chan_lantiq.c
- net/asterisk-11.x/src-lantiq/configs/lantiq.conf.sample
- net/asterisk-13.x/Makefile
- net/asterisk-13.x/src-lantiq/channels/chan_lantiq.c
- net/asterisk-13.x/src-lantiq/configs/samples/lantiq.conf.sample
Adds improved channel "chan_lantiq" (known from asterisk 1.8) to asterisk 11 and 13.
This enables usage of FXS ports from lantiq routers by asterisk.
> Feature chltq

- net/asterisk-13.x/Makefile
Signed-off-by: Roman Spychała <roed@onet.eu>
> asterisk-13.x: Add func_periodic_hook module

- net/freeswitch-stable/Config.in
- net/freeswitch-stable/Makefile
- net/freeswitch-stable/patches/140-libvpx-cross.patch
Hello all,
Please consider these 5 commits:
- freeswitch-stable: Fixes and housekeeping
- freeswitch-stable: Add some modules
- freeswitch-stable: Add fs_ivrd utility
- freeswitch-stable: Add Python support
- freeswitch-stable: Add options to include more libs
Thank you!
> Pull request for 5 commits

- net/freeswitch-stable/Makefile
Hello all,
Since the last batch of commits the package doesn't compile anymore because of a wrong host swig location. I hadn't realized it before because on my own computer the swig location was still correct. Anyway, sorry for that. Here is the fix and some other changes.
Thanks!
Sebastian
> PR for freeswitch-stable

- net/freeswitch-stable/Config.in
- net/freeswitch-stable/Makefile
- net/freeswitch-stable/patches/160-mod_lua-swig.patch
Hello @jslachta and @jow-,
Please consider this PR when you find the time. Thank you!
Kind regards,
Seb
> freeswitch-stable: new PR

- net/freeswitch-stable/Makefile
Hi all,
Please commit when you find the time.
Thanks!
Sebastian
> freeswitch-stable: Fix perl-esl deps

- libs/pjproject/Makefile
- libs/pjproject/patches/150-config_site.patch
- net/asterisk-13.x/Makefile
- net/asterisk-13.x/patches/054-pjsip_unresolved_symbol.patch
- net/asterisk-g72x/Makefile
- net/chan-sccp-b/Makefile
Here's the the PR I already wanted to send yesterday. I reworked it a little bit. I also added some extra commits for chan-sccp-b and asterisk-g72x.
Best regards,
Sebastian
> New PR: asterisk + pjproject

- libs/pjproject/Makefile
- net/asterisk-13.x/Makefile
- net/asterisk-13.x/files/asterisk.init
Hello everybody,
Mostly cleanups, but fixes as well.
Have a nice weekend!
Seb
> New PR: pjproject and asterisk13

- net/asterisk-13.x/Makefile
- net/asterisk-15.x/Makefile
Hi Jiri @jslachta ,
Didn't see these updates the last time around, otherwise I'd have updated all in one batch %)
Best regards,
Seb
> New PR: bump asterisk

- net/asterisk-13.x/Makefile
- net/asterisk-15.x/Makefile
These commits add support for external calendars plus fix a typo. With this PR issue #153 should be good to be closed.
Best regards,
Seb
> New PR: add calendar integration

- net/asterisk-g72x/Makefile
Hi Jiri,
This updates asterisk-g729 and adds a variant for Asterisk 15.
Kind regards,
Seb
> Asterisk g72x

- net/asterisk-13.x/Makefile
- net/asterisk-15.x/Makefile
Hello Jiri,
Just fixups/improvements, really. Version bump fixes some security issue with skinny, though.
Best regards,
Seb
> Asterisk: fixups, version bumps

- .github/issue_template
- .github/pull_request_template
The template will be used by issues and pull-request.
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>
> copy .github/templates from package feed

- net/freeswitch-stable/Config.in
- net/freeswitch-stable/Makefile
- net/freeswitch-stable/files/freeswitch.default
- net/freeswitch-stable/files/freeswitch.init
Maintainer: me
Compile tested: x86
Run tested: mips24
Description:
Nothing major, merely a bit of brushing up.
Kind regards,
Seb
> New PR: freeswitch-stable

- net/kamailio-3.x/Makefile
- net/kamailio-3.x/patches/150-CVE-2016-2385.patch
- net/kamailio-4.x/Makefile
Run tested: -
Description:
CVE fix for kamailio 3.x and a build fix for 4.x. As far as looking for open CVEs in 15.05 this is the last CVE I found.
Kind regards,
Seb
> Kamailio for 15.05

- net/asterisk-13.x/Makefile
Run tested: 
Description:
This fixes some glitches that I caught while creating the Asterisk pull request for lede-17.01
> asterisk-13.x: fix some dependencies

- net/freeswitch-stable/Makefile
Maintainer: me
Description:
Version bump
> freeswitch-stable: bump to 1.6.20

- net/yate/Makefile
Run tested:
Description:
Thanks god it's raining today and there's time for chasing down your own typos. :)
> yate: fix a typo

- net/yate/Makefile
- net/yate/patches/140-warning-unknown-architecture.patch
Compile tested: arc
Description:
Hi Jiri,
Thanks for patiently following up on my PRs! Appreciate it!
I hope this commits fixes the last yate compile issue :)
Kind regards,
Sebastian
> yate: turn miniwebrtc error into warning

- net/freeswitch-stable/Makefile
- net/freeswitch-stable/patches/330-do-not-install-freetdm-twice.patch
Maintainer: me
Description:
Some FreeTDM updates.
> freeswitch-stable: redo freetdm

- net/sipgrep/Makefile
Maintainer: me
Run tested: NA
Description:
fix typo
> net/sipgrep: fix PKG_SOURCE_URL

- net/yate/Makefile
Compile tested: x86_64, arc_archs, mips_24kc
Description:
Hi Jiri,
Stumbled over an OpenWrt variable to disable FORTIFY_SOURCE. It's better to use this than removing CPPFLAGS.
Regards,
Seb
> net/yate: some tiny updates

- net/asterisk-13.x/Makefile
- net/asterisk-15.x/Makefile
Run tested: NA
Description:
Hi Jiri,
Some Asterisk bumps.
Kind regards,
Seb
> Asterisk bumps

- net/kamailio-5.x/Makefile
Compile tested: mips24kc, x86_64
Description:
Hi Jiri,
After sleeping a night over yesterday's commit I think that some stuff I did with the libs/utils naming and placement should be improved.
Thanks!
Seb
> kamailio-5.x: update libs and utils handling

- libs/re/Makefile
- libs/re/patches/005-fix-builds-for-mipsel-targets.patch
- net/baresip/Makefile
Run tested: NA
Description:
Hi Jiri,
Some bumbs for baresip.
Kind regards,
Seb
> Re, Baresip: version bump

- libs/libpri/Makefile
Description:
Updates install defines
> libpri: update install defines

- net/yate/Makefile
Description:
Also not related to FPIC, just some updates.
> Yate updates

- libs/spandsp/Makefile
Description:
Removes FPIC, updates InstallDev define.
> Spandsp flags

- net/pcapsipdump/Makefile
- net/yate/Makefile
Run tested:
Description:
Hello Jiri,
The original commits were due to a misunderstanding on my part. Please revert.
Thanks!
Kind regards,
Seb
> Revert uclibc++ commits

- net/yate/Makefile
Compile tested: arc_archs
Description:
yate: add PKG_CONFIG_DEPENDS
> yate: add PKG_CONFIG_DEPENDS

- net/asterisk-chan-lantiq/Makefile
Compile tested:
Run tested:
Description:
Just a bump.
> asterisk-chan-lantiq: update snapshot

- libs/iksemel/Makefile
Compile tested: [Entware](https://github.com/Entware)
Run tested: Entware MIPSEL
> iksemel: use Google Storage API to get sources from former Googlecode

- net/asterisk-13.x/Makefile
- net/asterisk-13.x/patches/001-disable-semaphores-check.patch
- net/asterisk-13.x/patches/002-undef-res-ninit.patch
- net/asterisk-13.x/patches/052-musl-libcap.patch
- net/asterisk-13.x/patches/056-fix-check_expr2-build.patch
- net/asterisk-13.x/patches/100-build-reproducibly.patch
- net/asterisk-15.x/Makefile
- net/asterisk-15.x/patches/001-disable-semaphores-check.patch
- net/asterisk-15.x/patches/002-undef-res-ninit.patch
- net/asterisk-15.x/patches/004-disable-check-for-hrirs.patch
- net/asterisk-15.x/patches/056-fix-check_expr2-build.patch
- net/asterisk-15.x/patches/100-build-reproducibly.patch
Description:
Hi Jiri,
Also just version bumps.
Kind regards,
Seb
> Asterisk: version bumps

- net/asterisk-13.x/Makefile
- net/asterisk-13.x/patches/110-AST-2018-008-13.diff
- net/asterisk-15.x/Makefile
- net/asterisk-15.x/patches/110-AST-2018-007-15.diff
- net/asterisk-15.x/patches/120-AST-2018-008-15.diff
Compile tested: ar71xxx
Description:
Add patches for security advisories.
> (for OpenWrt 18.06): asterik: fix AST-2018-007 and AST-2018-008

- net/asterisk-13.x/Makefile
- net/asterisk-13.x/patches/110-AST-2018-008-13.diff
- net/asterisk-15.x/Makefile
- net/asterisk-15.x/patches/110-AST-2018-007-15.diff
- net/asterisk-15.x/patches/120-AST-2018-008-15.diff
Fixes
AST-2018-007 (15)
AST-2018-008 (13 and 15)
> (for master) asterik: fix AST-2018-007 and AST-2018-008

- net/freeswitch-stable/Makefile
- net/freeswitch-stable/patches/270-fix-uclibc-iconv-in-gsmopen.patch
- net/freeswitch-stable/patches/350-fix-pcre-pointer-type.patch
- net/freeswitch-stable/patches/360-fix-APR_TRY_COMPILE_NO_WARNING.patch
Maintainer: me
Description:
Backport recent fixes from master to 18.06.
> freeswitch-stable: backport fixes from master to 18.06

- net/asterisk-13.x/Makefile
- net/asterisk-13.x/patches/120-AST-2018-009-13.diff
- net/asterisk-15.x/Makefile
- net/asterisk-15.x/patches/130-AST-2018-009-15.diff
Description:
Hi Jiri,
This is a vuln fix for http_websocket module. I never used this particular module, so I didn't run-test this. Patch from upstream.
Kind regards,
Sebastian
> (Master) Fix for AST-2018-009

- net/asterisk-13.x/Makefile
- net/asterisk-13.x/patches/120-AST-2018-009-13.diff
- net/asterisk-15.x/Makefile
- net/asterisk-15.x/patches/130-AST-2018-009-15.diff
Description:
Same as for master.
> (18.06) Fix for AST-2018-009

- net/asterisk-13.x/Makefile
- net/asterisk-13.x/patches/070-AST-2018-009-13.diff
Compile tested: mips24kx
Description:
Same as for master.
> (17.01) Fix for AST-2018-009

- net/rtpproxy/Makefile
- net/rtpproxy/files/rtpproxy.config
- net/rtpproxy/files/rtpproxy.hotplug
- net/rtpproxy/files/rtpproxy.init
Run tested: ar71xx, dlink dir 825 c1, tested bridging RTP between private subnet and asterisk on public internet
Description:
Hello Jiri,
I put some effort into updating rtpproxy things while playing around with kamailio.
I hope you like the result :)
Kind regards,
Seb
> rtpproxy: update to procd and some brushing up

- net/sngrep/Makefile
- net/sngrep/patches/010-capture_-fix-typo-in-FILE-object.patch
- net/sngrep/patches/020-sip_-Do-not-crash-on-invalid-CSeq-values.patch
Maintainer: me
Description:
Update to 1.4.6
> sngrep: update to 1.4.6

- net/freeswitch-stable/Makefile
- net/freeswitch-stable/patches/390-switch-rtp_c-fix-implicit-declaration-of-function-RAND_bytes.patch
Maintainer: me
Description:
Fix compile and version bump.
> freeswitch-stable: fix compile, bump version

- net/baresip/Config.in
- net/baresip/Makefile
- net/baresip/files/baresip.init
- net/restund/Makefile
- net/restund/files/restund.init
Description:
Hello Jiri,
This updates the main application plus cleans up some things.
Kind regards,
Seb
> baresip: update and a bit of polishing

- net/asterisk-13.x/Makefile
- net/asterisk-13.x/patches/130-AST-2019-003-13.diff
- net/asterisk-15.x/Makefile
- net/asterisk-15.x/patches/160-AST-2019-003-15.diff
Compile tested: ar71xx 18.06
Description:
CVE fix
> (for 18.06) asterisk-1{3,5}.x: fix AST-2019-003

- libs/re/Makefile
- libs/rem/Makefile
- net/baresip/Makefile
- net/baresip/patches/002-fix-rem-include.patch
- net/restund/Makefile
Description:
Updated as per upstream request.
Resolves #474
> baresip suite: update to 0.6.4

- net/baresip/Makefile
Maintainer: me / @jslachta 
Compile tested: x86, master
Run tested: x86, master
Description:
This PR adds VP8 and VP9 module.
> baresip: add VP8 and VP9 module

- net/freeswitch-stable/Makefile
- net/freeswitch-stable/patches/390-t38-reinvite-488-fix.patch
Maintainer: me
Run tested: also ath79 master
Description:
Misc small fixes.
> freeswitch-stable: small misc fixes

- net/asterisk-16.x/Makefile
- net/asterisk-16.x/patches/AST-2019-006-16.diff
- net/asterisk-16.x/patches/AST-2019-007-16.diff
https://downloads.asterisk.org/pub/security/AST-2019-006.html
https://downloads.asterisk.org/pub/security/AST-2019-007.html
Run tested: N/A, no big changes, upstream security patches, should be fine.
Description:
Fixes security issues.
> [master] asterisk-16.x: add fixes for AST-2019-006 and 007

- libs/libks/Makefile
- libs/libks/patches/01-find-libm.patch
- libs/libks/patches/02-correct-signal_h-include.patch
- libs/libks/patches/03-fix-flags.patch
- libs/libks/patches/04-don_t-override-optimization.patch
- libs/signalwire-client-c/Makefile
- libs/signalwire-client-c/patches/01-set-libks-cmake-dir.patch
- net/freeswitch-stable/Makefile
Maintainer: me
Description:
Hi all,
**Please don't merge (yet)**. This is what I came up with regarding issue #413.
@skyblaster, do you want to run-test this and let us know afterwards your opinion regarding if and why this should be part of the telephony repo?
Regards,
Seb
> freeswitch-stable: add mod_signalwire and dependencies

- libs/libks/Makefile
- libs/libks/patches/01-find-libm.patch
- libs/libks/patches/02-correct-signal_h-include.patch
- libs/libks/patches/03-fix-flags.patch
- libs/libks/patches/04-don_t-override-optimization.patch
- libs/signalwire-client-c/Makefile
- libs/signalwire-client-c/patches/01-set-libks-cmake-dir.patch
- net/freeswitch-stable/Makefile
Maintainer: me
Run tested: done by skylaster on master
Description:
Cherry-pick commits from master.
> [19.07] freeswitch-stable: backport mod-signalwire + libs from master

- net/freeswitch/Makefile
- net/sipgrep/Makefile
Maintainer: me / @<github-user>
Run tested:  N/A
Description:
Some small cleanups.
> sipgrep/freeswitch: small amendments

- libs/libsrtp2/Makefile
- libs/libsrtp2/patches/010-gcc10.patch
> libsrtp2: fix compilation with GCC 10

- net/siproxd/Makefile
- net/siproxd/patches/020-gcc10.patch
> sixproxd: fix compilation with GCC 10

- libs/re/Makefile
- libs/re/patches/010-openssl-deprecated.patch
> re: fix compilation without deprecated OpenSSL APIs

- net/freeswitch/Makefile
- net/freeswitch/patches/400-fix-pc-file.patch
Maintainer: me
Description:
small fixes for #561 and hopefully #550
> freeswitch: small fixes

- libs/libpri/Makefile
- libs/libpri/patches/010-no-werror.patch
> libpri: remove Werror

- net/miax/Makefile
- net/miax/patches/010-usleep.patch
- net/miax/patches/020-includes.patch
> miax: fix compilation errors under uClibc-ng and musl

- libs/libosip2/Makefile
- net/siproxd/Makefile
Maintainer: none officially, maybe @guidosarducci  :)
Description:
Minor bump.
Hi Tony :)
Can I kindly ask you to runtest this when you get a chance? siproxd is the only user here. I bumped siproxd, too, because of soname change.
Kind regards,
Seb
P.S.: Not urgent!
> libosip2: minor version bump

- net/freeswitch/Makefile
- net/freeswitch/patches/420-time.patch
> freeswitch: fix compilation with musl 1.2.0

- libs/dahdi-linux/Makefile
- libs/dahdi-linux/patches/140-Use-proc_ops-on-kernels-5.6.patch
- libs/dahdi-linux/patches/141-Remove-support-for-32-bit-userspace-with-64-bit-kern.patch
- libs/dahdi-linux/patches/142-Remove-checks-for-HAVE_UNLOCKED_IOCTL-for-kernel-5.9.patch
Compile tested: mt7621, Linux 5.10
Relevant kernel commits:
https://github.com/torvalds/linux/commit/4e24566a134ea167441a1ffa3d439a27cf400880
https://github.com/torvalds/linux/commit/d56c0d45f0e27f814e87a1676b6bdccccbc252e9
> dahdi-linux: patch to compile with linux >= 5.6

- .github/workflows/Dockerfile
- .github/workflows/ci_helpers.sh
- .github/workflows/entrypoint.sh
- .github/workflows/formal.yml
- .github/workflows/multi-arch-test-build.yml
Perform formal checks and see if packages compile on multiple
architectures.
Signed-off-by: Paul Spooren <mail@aparcar.org>
> CI: add GitHub testing of Pull Requests

- libs/pjproject/Makefile
- libs/pjproject/patches/0070-fix-incorrect-copying-when-creating-cancel.patch
- libs/pjproject/patches/0070-fix-sdp-neg-modify-local-offer.patch
- libs/pjproject/patches/0080-fix-sdp-neg-modify-local-offer.patch
- net/asterisk/Makefile
- net/asterisk/patches/001-disable-semaphores-on-uclibc-otherwise-allow.patch
- net/asterisk/patches/002-configure-fix-detection-of-re-entrant-resolver-funct.patch
- net/asterisk/patches/100-build-reproducibly.patch
- net/asterisk/patches/130-eventfd.patch
- net/asterisk/patches/140-use-default-lua.patch
Description: Backports from master
> [21.02] asterisk backports

- libs/pjproject/Makefile
- libs/pjproject/patches/0090-Skip-unsupported-digest-algorithm-2408.patch
- libs/pjproject/patches/0100-fix-double-stun-free.patch
- libs/pjproject/patches/0110-tls-parent-listener-destroyed.patch
- net/asterisk/Makefile
Compile tested: master + 19.07 ath79
Run tested: 19.07 ath79
Description: Hi Jiri,
Minor bump + dep update + pjproject patch sync
Kind regards,
Seb
> asterisk: bump to 18.5.1

- libs/pjproject/Makefile
- libs/pjproject/patches/0090-Skip-unsupported-digest-algorithm-2408.patch
- libs/pjproject/patches/0100-fix-double-stun-free.patch
- libs/pjproject/patches/0110-tls-parent-listener-destroyed.patch
- net/asterisk/Makefile
Compile tested: 21.02 ath79
Run tested: 21.02 ath79
Description:
Hi Jiri,
I think this should go into openwrt-21.2 because of the 3 AST security notices.
Kind regards,
Seb
> [21.02] Backport Asterisk 18.5.1 bump

- net/asterisk/Makefile
Description:
Add some new modules + a missing dependency that were missed. Will wait with this and revdump later, not urgent. Just adding now to not forget.
> asterisk: add missing modules + dependency

- net/freeswitch/Makefile
- net/freeswitch/patches/460-remove-python-configure-checks.patch
- net/freeswitch/patches/480-fix-libyuv-dependency.patch
Maintainer: me
Run tested: N/A, changes do not change the packages
Resolve #704 
Description:
Hi @neheb,
Can you please try "freeswitch: don't check for distutils" commit on your Fedora?
Kind regards,
Seb
> freeswitch: build fix + patch update

- net/asterisk/files/asterisk.init
Description:
This cherry-picks the sighup commit from @dhewg's PR #701. Also the logger facility is changed from user to daemon, as was suggested in the same PR.
> asterisk: init script changes

- libs/pjproject/patches/0170-stun-integer-underflow.patch
- libs/pjproject/patches/0171-dialog-set-free.patch
- libs/pjproject/patches/0172-prevent-multipart-oob.patch
Details:
https://downloads.asterisk.org/pub/security/AST-2022-004.html
https://downloads.asterisk.org/pub/security/AST-2022-005.html
https://downloads.asterisk.org/pub/security/AST-2022-006.html
Compile tested: master SDK
Run tested: ath79 21.02
Description:
Incorporate upstream security fixes
> pjproject: add upstream security fixes

- libs/pjproject/Makefile
- libs/pjproject/patches/0170-stun-integer-underflow.patch
- libs/pjproject/patches/0171-dialog-set-free.patch
- libs/pjproject/patches/0172-prevent-multipart-oob.patch
Details:
https://downloads.asterisk.org/pub/security/AST-2022-004.html
https://downloads.asterisk.org/pub/security/AST-2022-005.html
https://downloads.asterisk.org/pub/security/AST-2022-006.html
(cherry picked from commit 623e5288f16baa64472eefbbd215aacb0f99e79f)
Compile tested: 19.07.9 SDK
Run tested: 21.02.2 ath79
Description: Cherry-pick from master, incremented PKG_RELEASE.
> [19.07] pjproject: add upstream security fixes

- libs/pjproject/Makefile
- libs/pjproject/patches/0130-sip_inv-Additional-multipart-support-2919-2920.patch
- libs/pjproject/patches/0140-Fix-incorrect-unescaping-of-tokens-during-parsing-29.patch
- libs/pjproject/patches/0150-Create-generic-pjsip_hdr_find-functions.patch
- libs/pjproject/patches/0160-Additional-multipart-improvements.patch
- net/asterisk-16.x/Makefile
- net/asterisk-16.x/patches/001-disable-semaphores-on-uclibc-otherwise-allow.patch
- net/asterisk-16.x/patches/002-configure-fix-detection-of-re-entrant-resolver-funct.patch
- net/asterisk-16.x/patches/100-build-reproducibly.patch
- net/asterisk-16.x/patches/130-eventfd.patch
- net/asterisk-16.x/patches/160-AST_EXT_TOOL_CHECK.patch
- net/asterisk-16.x/patches/180_build-fix-bininstall-launchd-issue-on-cross-platfrom.patch
Compile tested: 19.07 ath70 SDK
Run tested: N/A, don't have a router with 19.07 installed
Description: bump to address AST-2022-00{1,2,3} in 19.07 branch.
Thanks!
> [19.07] asterish-16.x: bump to 16.25.2

- .github/issue_template
- .github/pull_request_template
- .github/workflows/Dockerfile
- .github/workflows/entrypoint.sh
- .github/workflows/multi-arch-test-build.yml
Description:
Sync our CI to packages repo. All changes in commit message.
Hi Jiri, if you're OK with this please merge.
> CI: sync up with changes in packages repo

- libs/pjproject/Makefile
- libs/pjproject/patches/0200-potential-buffer-overflow-in-pjlib-scanner-and-pjmedia.patch
- libs/pjproject/patches/0201-potential-stack-buffer-overflow-when-parsing-message-as-a-STUN-client.patch
- net/asterisk/Makefile
Compile tested: sdk master
Description:
Fixes
AST-2022-007
AST-2022-008
AST-2022-009
I dropped AUTORELEASE from both asterisk and pjproject as OpenWrt project wants to get rid of it.
Kind regards,
Seb
> asterisk: bump to 20.0.1

- libs/freetdm/Makefile
- libs/freetdm/patches/900-mod_freetdm-Adapt-to-new-PCRE2-API.patch
Backport of https://github.com/openwrt/telephony/pull/887
Fixes: https://github.com/openwrt/telephony/issues/902
> [24.10] freetdm: add patch for PCRE2 support
