libs/dahdi-linux/patches/001-include-slab-h-in-oct612x-user-c.patch

Unbreak dahdi-linux build at least for cns3xxx, kirkwood, mvebu and oxnas
by explicitely including slab.h in oct612x-user.c.

dahdi-linux: fix oct612x compile on some ARM targets

---

libs/dahdi-linux/patches/002-backport-smp_mb__after_atomic.patch

smp_mb__after_clear_bit() was removed from newer kernels.
Use smp_mb__after_atomic() instead.
Spotted on buildbot on targets using kernel 3.18:
.../dahdi-linux-2.10.0.1/drivers/dahdi/wcte13xp-base.c: In function 't13x_set_linemode':
.../dahdi-linux-2.10.0.1/drivers/dahdi/wcte13xp-base.c:1852:2: error: implicit declaration of function 'smp_mb__after_clear_bit' [-Werror=implicit-function-declaration]
smp_mb__after_clear_bit();
^

dahdi-linux: fix build with kernel 3.15 and newer

---

libs/dahdi-linux/Makefile
libs/dahdi-linux/patches/100-add-support-for-hfc-s-pci.patch

dahdi-hfcs driver from sf.net => works nicely.
I also had a look at openvox.cn, won't touch it unless someone really needs it...
I'd be more happy to port switchfin or rowetel stuff (anyone got spare hardware?)

dahdi-linux: add support for HFC-S PCI BRI adapters

---

net/asterisk-11.x/Makefile

on Arch Linux configure find host mysql_config first
set location explicitly to fix build fail
Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>

asterisk-11.x: fix mysql_config location

---

net/asterisk-13.x/Makefile

on Arch Linux libxml2 detection fails
set xml2-location explicitly to fix build fail
Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>

asterisk-13.x: fix xml2-config location

---

net/asterisk-11.x/Makefile

Shorten Package Description for easier readability when displaying "pkg list | grep asterisk11"

Update Asterisk11 Makefile (Untested)

---

libs/bcg729/Makefile

Anyone still got the old tarball in their download folder? PLEASE make a diff and post it here, so we can see what actually changed.

bcg729: source tarball MD5 changed mysteriously

---

net/asterisk-13.x/Makefile

Add the missing Confbridge and it brings the bridge_simple.so to activate the sip module.
Without the bridge_simple.so can not make calls via sip it.
Signed-off-by: Sven Pietack <redfox1977@users.noreply.github.com>

Asterisk13.x: Add missing Confbridge

---

net/asterisk-13.x/Makefile

Add the depensies for the chan_sip modul bacause chan_sip dos not function with out it.
Signed-off-by: Sven Pietack <redfox1977@users.noreply.github.com>

Asterisk 13.x: Add depensies for chan_sip

---

libs/dahdi-linux/Makefile

It would result in the warning "echo is already loaded" during package installation.

Avoid trying to load the echo module from kmod-dahdi-echocan-oslec

---

net/asterisk-11.x/patches/010-asterisk-configure-undef-res-ninit.patch

Lately configure is recreated from configure.ac. The current patch changes configure. So we patch it, then it gets recreated and our change is gone. So patch configure.ac instead. Without this change the build fails due to an undefined reference to res_nsearch.

asterisk-11x: Update 010-asterisk-configure-undef-res-ninit.patch

---

net/asterisk-11.x/Makefile

The configure script generated by bootstrap.sh in the menuselect folder doesn't work properly. It doesn't check for 'sed', for instance, resulting in './configure: line 4622: -e: command not found'. The build works well without the bootstrap.

asterisk-11.x: Don't bootstrap menuselect

---

net/siproxd/Makefile
net/siproxd/patches/100-musl-compat.patch

- Add missing `sys/types.h` include to provide `u_short` type under musl
- Add missing `string.h` includes to avoid implicit function declarations
Signed-off-by: Jo-Philipp Wich <jow@openwrt.org>

siproxd: fix musl compatibility

---

net/sipp/Makefile
net/sipp/patches/100-musl-compat.patch

Always include `sys/types.h` as it is basically required by anything besides
Glibc and uClibc. Fixes build against musl.
Signed-off-by: Jo-Philipp Wich <jow@openwrt.org>

sipp: fix musl compatibility

---

net/miax/patches/003-musl-fixes.patch

- error.h does not seem to be used (musl doesnt provide one)
fixes error/handling of FILE *stderr leading to errors like:
miax.c:217:2: error: assignment of read-only variable 'stderr'
stderr=fopen(log_output,"w");
thx to jow for pointing things out
Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>

miax: fix musl build

---

net/asterisk-11.x/Makefile

asterisk-11.x: Bump to 11.19.0

---

libs/iksemel/Makefile
libs/iksemel/patches/002-use-of-newer-gnutls_priority_set_direct-api.patch
net/asterisk-1.8.x/Makefile
net/asterisk-11.x/Makefile
net/asterisk-13.x/Makefile

Added a patch to iksemel that allows it compile against gnutls 3.4.x.  It was previously broken because it used some depreciated APIs.
I've tested this patch on asterisk-11, running on my Netgear R7000 (armv7).  It restores my Asterisk connectivity with Google Voice.
I'd love to see it included in the `telephony` feed and future updates.

iksemel: restore package and all dependent asterisk modules

---

net/chan-sccp-b/Makefile

New Features in V4.2.3
- Warning about use of ancient gcc compiler
- New desktop/background images
- New AMI Function:SCCPShowRefcount
- Support for newer/future version of automake
- Small size reduction of chan_sccp.so
Bug Fixes
- Channel being left behind after hangup
- Scheduled Hangup / Schedule Digit Timeout
- Potential Deadlock Fallback Atomic Functions
- MWI loosing track of new voicemails under certain circumstances
- using gnu version of libiconv fixed
- gen_sccp_enum improved / gnu awk extension dependency removed
- set socket option should happen before binding to the socket
- channel monitor/record handling fixed
- Code cleanup / fixed memory leaks / fixed potential null pointer dereferences
- Some smaller patches (Check ChangeLog for details)

Chan-sccp-b release v4.2.3

---

net/freeswitch/Config.in
net/freeswitch/Makefile

this leads to lots of these lines when updating the feed in CC
WARNING: No feed for package 'libsqlite2' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libedit' found, maybe it's already part of the standard packages?
Signed-off-by: John Crispin <blogic@openwrt.org>

freeswitch: libsqlite2 and libedit do not exist

---

libs/libpri/Makefile

Fixes build, 1.4.15 version was moved to old/ dir.
Signed-off-by: Mantas Pucka <mantas@8devices.com>

libpri: add old release dir to mirrors

---

libs/re/Makefile

Compile tested on: Kirkwood, LEDE trunk
Adds missing zlib dependency
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

libs/re: Add zlib dependency

---

net/yate/Makefile

Compile tested on: Kirkwood, LEDE trunk
Remove Speex as it's being obsoleted by upstream.
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

net/yate: Remove support for Speex

---

net/freeswitch/Makefile

libedit is not available in 15.05. Add --disable-core-libedit-support
to configure flags to fix build error
Fixes #118
Signed-Off-By: Bernhard Schmidt berni@birkenwald.de

Fix build of FreeSWITCH due to missing libedit

---

net/baresip/Makefile

Compile tested on: Kirkwood, LEDE trunk
Remove Speex as it's being obsoleted by upstream.
Add Opus to replace Speex
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

net/baresip: Update to 0.5.0

---

net/freeswitch-stable-sounds/Makefile

- Fixed sha256 checksums of some of the Russian language prompts
- Commented out non 8 kHz sound packs to not clog the mirrors
- Changed versioning scheme to the one used by upstream
- Made "Sounds" function params more generic

freeswitch-stable-sounds: General fixes

---

net/pcapsipdump/Makefile

Make sure that we properly pass down both TARGET_CPPFLAGS and
TARGET_LDFLAGS in order to fix build failures with external toolchains
that don't automatically search for headers and libraries in
$(STAGING_DIR).
Signed-off-by: Florian Fainelli <f.fainelli@gmail.com>

pcapsipdump: Pass down TARGET_CPPFLAGS and TARGET_LDFLAGS

---

libs/libpri/Makefile

The 1.4.15 file has been moved into an /old/ subfolder

Fix PKG_SOURCE_URL for libpri 1.4.15

---

net/yate/patches/120-create-thread-key-on-access.patch

pthread_key_create used to be called when a specific static key object was
initialized, but if another static object was initialized earlier and this
other object needed the key during its initialization yate would crash.
Fixes #99
Signed-off-by: Robert Högberg robert.hogberg@gmail.com

yate: Call pthread_key_create when the key is first accessed

---

net/yate/Makefile

Yate.pm that is included in yate-scripts-perl uses perl package Data::Dumper
which is provided by openwrt package perlbase-data. Update dependency to
reflect this.
Signed-off-by: Robert Högberg robert.hogberg@gmail.com

yate-scripts-perl: Add dependency on perlbase-data

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/150-erlang-m4.patch

Now that the swig location is fixed the build dies someplace else, at erlang. I (hopefully) fixed erlang, and I assume with python we would run into the same issue, so here a PR with an erlang and a python fix.
@jow- I know you're busy, but maybe if you get around to it... :) Thank you

PR for freeswitch-stable

---

net/freeswitch-stable/Makefile

- mod_unimrcp picked up external apr/apr-util if found in the target
directory, which caused the build to fail (undefined references). Fixed
by adding the FreeSWITCH apr/apr-util lib dirs to the front of LDFLAGS.
Hello @jow-, I'm almost sure this is the last one. Could you please merge it? Thank you!

freeswitch-stable: Fix mod_unimrcp build failure

---

libs/spandsp/Makefile
libs/spandsp/patches/101-disable-fixed-point.patch

On a Netgear R7000 (ARMv7) without floating point, using SpanDSP with
fixed point to send/receive fax on Asterisk resulted in repeated
failure and intermittent performance.  Disabling fixed point fixed
these issues; the software floating point implementation was fine for
real-time use.
Now on a Netgear R7800 (ARMv7) with hardware floating point, the
autoconf auto-detect will say no floating point is available, and
again enables the poor performing fixed point implementation.  Ouch!

spandsp: disable fixed point implementation

---

net/yate/Makefile

echo.sh is a simple yate script which can be used to echo back audio to a
caller. It's useful for testing purposes.
Since the script is a basic shell script it has no specific dependencies.
Signed-off-by: Robert Högberg robert.hogberg@gmail.com
---
I think it would be good to include this script by default in the package because:
- It's small
- It has no dependencies
- It's useful to verify two-way audio
There are other shell scripts shipped with yate which could be included also (noise.sh, play.sh and test.sh) but I don't find them as useful and play.sh has a dependency on sox.

yate-mod-extmodule: Include and install script echo.sh

---

net/freeswitch-stable/Makefile

Hello again @jslachta and @jow- 
I messed up a Python mk include in my previous PR. Sorry for that.
Here's the fix. I hope this is the only issue. :)
Kind regards,
Sebastian

freeswitch-stable: Fix python-host.mk include

---

libs/bcg729/Makefile
libs/pjproject/Makefile
net/asterisk-11.x/Makefile
net/asterisk-11.x/patches/010-asterisk-configure-undef-res-ninit.patch
net/asterisk-11.x/patches/052-musl-libcap.patch
net/asterisk-11.x/patches/054-fix-cross-compile.patch
net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/001-disable-semaphores-check.patch
net/asterisk-13.x/patches/002-undef-res-ninit.patch
net/asterisk-13.x/patches/052-musl-libcap.patch
net/asterisk-13.x/patches/054-fix-cross-compile.patch
net/asterisk-g72x/Makefile
net/freeswitch-stable-mod-bcg729/Makefile

I wanted to add a module that links against bcg729, for which I needed a version bump. So I updated the asterisk module along with it. Asterisk didn't really compile in trunk so I went and fixed what I found until it compiled and I could compile-test asterisk-g72x.
I read in some of the issue reports that asterisk has some issues loading modules on musl (missing symbols), but I couldn't reproduce that. I loaded a few modules and it worked fine.
Best regards,
Sebastian

New PR: mostly Asterisk (bumps, fixes, new package too)

---

net/yate/Makefile
net/yate/files/banbrutes.pl

Yate ships with a php script (banbrutes.php) which can help block brute
force login/password attacks. Since Yate for OpenWrt doesn't support
php scripts I've written a similar script in perl that's easier to use
with OpenWrt.
The script uses the iptables extension "recent" to keep track of
authentication failures and block users after too many authentication
failures.
This is an alternative to #87. The functionality is mostly the same,
but this is a slightly simplified, more light-weight version since
IP sets aren't used.
Signed-off-by: Robert Högberg robert.hogberg@gmail.com

yate-scripts-perl: Add script to block phones which fail to authenticate

---

net/asterisk-11.x/Makefile
net/asterisk-11.x/files/asterisk.init
net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/054-pjsip_unresolved_symbol.patch
net/asterisk-13.x/patches/055-ASTERISK-24517.patch

Hi Jiri @jslachta 
This basically does the same cleanups to 11 that were done to 13. Couldn't be done 100% the same because in 11 the bundled pjproject would get in the way a bit otherwise.
For 11 it also turned out that libedit needs to stay internal :( Anyway...
For 13 I added a patch from alpine linux to fix issue #185.
Regarding the recently spotted segfault in 11 (in res_rtp_asterisk.so) I don't know. I started compiling with debug enabled but then the segfault went away.
Kind regards,
Seb

New PR: asterisk 11 + 13 (cleanups, fixes and version bumps)

---

net/asterisk-chan-lantiq/Makefile

When building using the SDK the $(SOURCE) variable is set differently,
resulting in files not being found. Not using the variable and using
"./" instead works fine.
This fixes issue #190. Thanks to @Bongo79 for reporting and providing
the fix.

asterisk-chan-lantiq: fix SDK build

---

net/kamailio-4.x/Makefile
net/kamailio-4.x/patches/050-fix-kamailio-utils.patch
net/kamailio-4.x/patches/110-include-sys-time-h-in-ld_session-h.patch
net/kamailio-4.x/patches/111-include-sys-time-h-in-sercmd-c.patch
net/kamailio-4.x/patches/120-libevent-libs.patch

Compile-tested on: CC/adm8668
Description:
Fix build on CC, while at it, upgrade to 4.4.0. mod-dialog-ng had to be pulled from the modules as it's not available in the source, and the sercmd patch had to be manually updated to patch kamcmd instead.

CC: kamailio-4.x: upgrade to 4.4.0, fix build

---

net/asterisk-13.x/Makefile
net/asterisk-15.x/Makefile
net/asterisk-chan-lantiq/Makefile

Hello @jslachta 
I'm not sure what you got queued up for chan-lantiq. If this doesn't get in the way of anything please consider merging it.
Kind regards,
Seb
The previously conceived hack - to make the buildbots actually build
this package during the target phase - does not work. This patch removes
the hack. This includes removing the lines from the asterisk Makefiles
that tar up the asterisk headers.
The upside of removing the hack is that the package name can be reverted
to what it was before, so it can be found in the same place like all the
other asterisk modules, i.e. below its asterisk version.
Another upside is that the Makefile does not pretend to solve the
problem anymore. Issue #193 is still open for the same. Maybe some day
somebody can figure out how to resolve the problem …

asterisk-chan-lantiq: remove nonshared hack

---

net/asterisk-chan-dongle/Makefile

chan-dongle already supports asterisk 15. This commit adds a variant for
it.

chan-dongle: add variant for asterisk 15

---

libs/re/Makefile
libs/re/patches/002-fix-redefine-ssize_t.patch
libs/re/patches/003-fix-linker-call.patch
libs/re/patches/004-prevent-optimization-meddling.patch
libs/rem/Makefile
net/baresip/Makefile
net/baresip/patches/001-fix-linker-call.patch
net/baresip/patches/002-fix-rem-include.patch
net/restund/Makefile
net/restund/patches/001-fix-linker-call.patch

These commits change the Build/Compile routine to the default one for all four packages. This has the benefit of using the standard features like FORTIFY_SOURCE and RELRO. Also cleanups where done, modules added and the build failure of baresip that is currently happening is also fixed.
Best regards,
Seb

New PR: re, rem, restund and baresip

---

net/baresip/Makefile

The avcodec module needs a depend on libx264.

baresip: add missing dependency

---

net/asterisk-15.x/Makefile
net/asterisk-15.x/patches/053-musl-mutex-init.patch

@kochstefan pointed out that asterisk 15 doesn't load any modules. It
turned out that this happens because of patch that was dropped. Add the
patch again.

asterisk-15.x: add 053-musl-mutex-init.patch

---

net/asterisk-13.x/Makefile
net/asterisk-15.x/Makefile

Hi Jiri.
I think this is a cool feature. First it disables all modules that get enabled by default, then it enables the modules required for the selected packages. Benefits are that stuff we don't need for the packages isn't built (so the build takes less time) and that there are modules that might be added in the future that are not enabled by default and this mechanism automatically takes care of enabling them.
This doesn't touch the compiler settings or sound files. Just the items that are actually compiled.
Kind regards,
Seb

Asterisk: Prevent building of all default modules

---

net/asterisk-chan-lantiq/Makefile

Hi Jiri,
This commit unpacks the sources of lib_ifxos, drv_tapi and drv_vmmc,
patches them and sets up their header files for the compiler to use when
building chan-lantiq.
The dependency on kmod-ltq-vmmc is dropped so that the package can be
built by the buildbots. Instead, a dependency on mips is added so that
the buildbots will only build the package for the ARCH that Lantiq
actually runs on.

chan-lantiq: setup Lantiq kernel headers locally

---

net/asterisk-chan-lantiq/Makefile

Hi all,
Unfortunately the hack didn't work out. So this commit reverts it.
On another, more positive note, there's now also a variant for Asterisk 15.
Best regards,
Sebastian

chan-lantiq: revert (non-working) hack, add Asterisk 15 variant

---

net/sipp/Makefile
net/sipp/patches/110-reproducible-builds.patch

Build timestamps prevent reproducible builds [0].
[0] https://reproducible-builds.org/docs/timestamps/
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

sipp: remove build timestamp

---

net/restund/Makefile
net/restund/patches/100-reproducible-builds.patch

Build timestamps prevent reproducible builds [0].
[0] https://reproducible-builds.org/docs/timestamps/
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

restund: remove build timestamp

---

net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/100-build-reproducibly.patch
net/asterisk-15.x/Makefile
net/asterisk-15.x/patches/100-build-reproducibly.patch
net/asterisk-chan-sccp/Makefile
net/asterisk-chan-sccp/patches/100-reproducible-builds.patch

Remove build timestamp to make it reproducible.

asterisk: reproducible builds

---

net/kamailio-5.x/Makefile

Compile tested: lantiq, LEDE master
Build timestamps prevent reproducible builds [0].
[0] https://reproducible-builds.org/docs/timestamps/
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

kamailio-5.x: remove build timestamp

---

libs/re/patches/005-fix-builds-for-mipsel-targets.patch
net/baresip/Config.in
net/baresip/Makefile

Compile tested: mipsel, i386
Run tested: -
Description: fixes re build failures on mipsel targets and prevents baresip build failures on arm, mips etc.
Kind regards,
Seb

baresip/re: build fix and a workaround

---

libs/bcg729/Makefile

- the Savannah source URI doesn't have the 1.0.4 release; switch it to
linphone.org
- even with the source available the build fails, as the source now
defaults to cmake for building. So switch our build process from
autotools to cmake as well.
Run tested: -
Description:
Fixes the bcg729 build

bcg729: fix 1.0.4 build

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/280-tone-down-freetdm-COMP_VENDOR_CFLAGS.patch
net/freeswitch-stable/patches/290-fix-mod_freetdm-copts.patch

Maintainer: me
Compile tested: arc, mips_24kc, x86_64
Run tested: none (don't have the TDM hardware)
Description:
This pull request adds FreeTDM support to the FreeSWITCH packages. OpenWrt has already proper DAHDI support and FreeTDM is the bridge to that for FreeSWITCH.

freeswitch-stable: Add FreeTDM support

---

libs/gsmlib/Makefile
libs/gsmlib/patches/01-update-autotools.patch
libs/gsmlib/patches/02-fix-cross-compile.patch
libs/gsmlib/patches/03-disable-Siemens-specific-code.patch
libs/libctb/Makefile
net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/270-fix-uclibc-iconv-in-gsmopen.patch

Maintainer: me
Compile tested: arc, mips_24kc and x86_64
Run tested: don't have the hardware
Description:
Hi all,
I'd like to add gsmlib and libctb. Both are needed for mod_gsmopen in FreeSWITCH. The packages aren't available for OpenWrt yet.
mod_gsmopen is for FreeSWITCH what chan-dongle is for Asterisk. Having the option to use your PBX as a GSM gateway is nice, e.g. for making test calls etc. (or just making normal phones calls via GSM and sending/receiving SMS).
gsmlib: A library to access GSM mobile phones via GSM modems
libctb: Communications toolbox - ctb
Both libs are admittedly a bit dated already. But they are hard dependencies of mod_gsmopen.
Please let me know if you have any concerns or doubts. Otherwise I'd like to merge these commits the coming weekend.
Best regards.
Seb

New PR: add gsmlib, libctb and mod_gsmopen

---

libs/gsmlib/Makefile

Maintainer: me
Run tested: -
Description: fix a build failure

gsmlib: fix sporadic build failures

---

libs/libosip2/Makefile
libs/libosip2/patches/01-CVE-2017-7853.patch

Maintainer: @jslachta (actually package doesn't have a maintainer line currently)
Run tested: -
Description: fix security bug.

libosip2: add fix for CVE-2017-7853

---

net/freeswitch-stable/Makefile

This was suggested in PR #241 by @commodo. Python maintainers moved the
.mk files and also want to get rid of the include_mk construct.
Maintainer: me
Description: see commit

freeswitch-stable: change how python-host.mk is included

---

libs/dahdi-tools/Makefile

Compile tested: arc700
Run tested: (don't have the hardware)
Description:
Hi Jiri,
This is one of the reasons asterisk fails to build on ARC (uclibc) in lede-17.01. For the other two reasons I sent PRs to the package maintainers (alsa + sqlite3).
Kind regards,
Sebastian

dahdi-tools: Fix dahdi dependency on lede-17.01

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/120-fix-copts.diff
net/freeswitch-stable/patches/310-use-system-tiff.patch
net/freeswitch-stable/patches/311-use-system-tiff.patch
net/freeswitch-stable/patches/312-use-system-tiff.patch
net/freeswitch-stable/patches/313-use-system-tiff.patch
net/freeswitch-stable/patches/314-use-system-tiff.patch

Maintainer: me
Description: Use system libtiff instead of bundled copy

freeswitch-stable: use system libtiff

---

libs/libosip2/Makefile

ARC toolchain exports __arc__, which clashes with a symbol of the same
name in libosip2. This commit undefines the toolchain symbol when
building the library.
The fix was found in buildroot repo. Thanks to whoever spotted this!
Compile tested: (put here arch, model, OpenWRT/LEDE version)
Run tested: (put here arch, model, OpenWRT/LEDE version, tests done)
Description:
Hi Jiri,
Just a build fix.
Kind regards,
Seb

libosip2: fix build with ARC toolchain

---

libs/dahdi-linux/Makefile

Compile tested: arm_mpcore
Description:
Hi Jiri,
on targets with kernel 4.14 dahdl-linux fails to build (snapshots), causing follow-up breakage. I suggest to temporarily use a git snapshot to work around this until upstream makes a new releases that includes the fixes.
I tried cherry-picking but couldn't get it to work. The snapshot build works, though (build-tested only).
Kind regards,
Seb

dahdi-linux: update source to snapshot

---

net/kamailio-5.x/Makefile
net/yate/Makefile

Description:
Hi Jiri,
There is a bit of fallout after the yate series. Basically I had tested the commits on arc_archs and there they worked. But apparently there the fortify-source headers are actually not available or just different (uClibc related maybe).
Anyway, on other targets there is build failures when compiling against fortify-headers. The yate commit addresses that.
And the 2nd commit is just something I found a bit later. Saves some space in the package.
;-)
Kind regards,
Seb

PR: yate follow-up and a bit of kamailio

---

net/freeswitch/Makefile

Disable also flite module that depends on a non-existing package.
Mazilo fixed all other modules that had wrong dependencies, with be557c9bc07dd , but apparently forgot about flite. It still causes the config warning for all Openwrt/LEDE build system users.
Disable it as I suggested in #250 and mazilo did with be557c9bc07dd for other deps
Maintainer: mazilo

freeswitch: disable flite module

---

net/pcapsipdump/Makefile

Compile tested: x86_64, mips24kc, arc_archs
Description:
Hi Jiri,
This removes the uclibc include from pcapsipdump as well.
Kind regards,
Seb

Pcapsipdump update

---

net/rtpproxy/Makefile
net/rtpproxy/patches/102-don-t-build-rtpproxy_debug.patch
net/rtpproxy/patches/103-add-missing-includes.patch

Compile tested: x86_64, mips24kc
Run tested: mips_24kc
Description:
Hello Jiri,
rtpproxy 2.0.0 branch hasn't been updated in a while upstream. Update to 2.1.0 which received last fixes end of last year.
Kind regards,
Seb

Rtpproxy bump

---

libs/dahdi-linux/patches/110-fix-uaccess_h-include.patch

Compile tested: mips64_octeon, x86_64
Description:
Hi Jiri,
found another build failure with newer kernels in dahdi-linux. Somebody already fixed the same for a different software, so I could just copy/paste, basically.
Kind regards,
Seb

dahdi-linux: include linux/uaccess.h rather than asm/uaccess.h

---

libs/bcg729/Makefile

As of 2017, all patents have expired. Full announcement text below:
As of January 1, 2017 the patent terms of most Licensed Patents under the G.729 Consortium have expired.
With regard to the unexpired Licensed Copyrights and Licensed Patents of the G.729 Consortium Patent License Agreement, the Licensors of the G.729 Consortium, namely Orange SA, Nippon Telegraph and Telephone Corporation and Université de Sherbrooke (“Licensors”) have agreed to license the same under the existing terms on a royalty-free basis starting January 1, 2017.
For current Licensees of the G.729 Consortium Patent License Agreement, no reports and no payments will be due for Licensed Products Sold or otherwise distributed as of January 1, 2017.

bcg729: Remove BUILD_PATENTED.

---

libs/libsrtp/Makefile

Description:
Removes FPIC and installs missing symlink.

Libsrtp flags and missing symlink

---

libs/gsmlib/Makefile

Maintainer: me
Description:
Still seeing sporadic build failures. This should fix it.

gsmlib: update PKG_BUILD_DEPENDS

---

libs/libosip2/Makefile

Description:
Removes FPIC and updates an install define.

Libosip2 flags and defines

---

libs/gsmlib/Makefile
libs/libctb/Makefile
net/freeswitch-stable/Makefile

Maintainer: me
Compile tested: x86_64 + mips_24kc
Run tested: mips_24kc
Description:
Switches from hardcoding libstdcpp use to use whatever standard C++ lib has preference (default uclibc++).

Follow user standard C++ lib selection

---

net/pcapsipdump/Makefile

Previous revert only works when libstdcpp is the default C++ lib. To
make the compile work in all scenarios LIBS needs to be defined and
MAKE_FLAGS are required instead of MAKE_VARS, otherwise the included
variables are overridden.
Run tested:
Description:
Meh, looks like my testing of the previous commit was only half-baked.
Kind regards,
Seb

pcapsipdump: compile fixes

---

libs/pjproject/Makefile

It is unlikely that SOFT_FLOAT is toggled, but add it to
PKG_CONFIG_DEPENDS for completeness' sake anyway.

pjproject: add PKG_CONFIG_DEPENDS

---

net/asterisk-chan-sccp/Makefile

Compile tested: x86_64 + arc_archs
Description:
Bump the snapshot plus remove a workaround that is not needed anymore.

asterisk-chan-sccp: bump and cleanup

---

net/asterisk-chan-dongle/Makefile
net/asterisk-chan-dongle/patches/300-use-openwrt-flags.patch

Maintainer: @jsla
Compile tested: x86_64 and arch_archs
Description:
Hello Jiri,
Simplifies the Makefile. Also updates to a current snapshot.
Regards,
Seb

asterisk-chan-dongle: simplify and update snapshot

---

libs/pjproject/Makefile
libs/pjproject/patches/160-remove-hardcoded-lstdc++.patch
net/asterisk-13.x/Makefile
net/asterisk-15.x/Makefile

Compile tested: x86_64, mips_24kc
Run tested: mips_24kc
Description:
Hi Jiri,
This removes the hardcoding of libstdcpp in the Asterisk and pjproject packages. If the preference is libuClibc++ it uses that instead. On OpenWrt libuClibc++ is default. It's about 1 MByte smaller on the router than libstdc++ and uses less RAM.
I've tested both 13 and 15, making phone calls both via chan_sip and pjsip. All OK.
The pull request also fixes some depends.
Kind regards,
Seb

Asterisk standard c++ lib

---

net/sipp/Makefile

Currently libstdc++ is hardcoded. Change that and use whatever standard
C++ lib has preference.
Compile tested: x86_64 + mips_24kc
Run tested: mips_24kc
Description:
Same as in the other PR for asterisk, removes the hardcoded dep on libstdcpp.

sipp: use preferred standard C++ lib

---

net/siproxd/files/siproxd.config
net/siproxd/files/siproxd.init
net/siproxd/patches/010-syslog-msg.patch

Compile tested: ar71xx/mips24kc
Run tested: ar71xx/mips24kc under LEDE 17.01.4
Description:
Hi Jiri,
This PR includes the few changes discussed as part of #283 , including some UCI default config improvements suggested by @micmac1 .
The switchover to using callbacks to parse the UCI config file also exposed some 6-year-old related problems, which I've fixed and tested as part of https://github.com/openwrt/openwrt/pull/805. I'd appreciate if you could review that PR and comment as needed.
Note that the other PR is not a strict dependency for the current PR. The upstream callback problems result in spurious config file entries which, thankfully, siproxd ignores. However, those issues have likely caused historical problems for people making non-trivial use of callbacks, …

siproxd init code and usability improvements

---

net/baresip/Makefile

There are two pulseaudio packages, pulseaudio-daemon and
pulseaudio-daemon-avahi. Both provide pulseaudio. Depend on pulseaudio
so the user may choose which one to install.
Description:
Hi Jiri,
This cleans up the depend of mod-pulse.
Kind regards,
Seb

baresip: update baresip-mod-pulse depend

---

net/baresip/Makefile

mod-avformat is only built when mod-avcodec is selected. baresip sets it
up like that in mk/modules.mk:
```
ifneq ($(USE_AVCODEC),)
MODULES   += avcodec
ifneq ($(USE_AVFORMAT),)
MODULES   += avformat
endif
endif
```
This commit updates the mod-avformat DEPENDS accordingly.
Compile tested: arc_archs
Description:
Hello Jiri,
Just a DEPENDS fix.
Thanks!
Seb

baresip: fix mod-avformat DEPENDS

---

net/freeswitch-stable/Makefile

Underscores should not be used in package base names as they're used as
semantic separators by opkg.
Maintainer: me
Description:
Fix package names

freeswitch-stable: remove underscores from package names

---

net/asterisk-13.x/Makefile
net/asterisk-15.x/Makefile

Description:
Hello Jiri,
Jo mentioned in [this pull request](https://github.com/openwrt/packages/pull/5851) that "underscores should not be used in package bas (sic) names as they're used as semantic separators by opkg".
So I found a few packages with underscores in their base name. I'll send the remaining pull requests soon.
Kind regards,
Seb

Asterisk: fix package names

---

net/yate/Makefile

Underscores should not be used in package base names as they're used as
semantic separators by opkg.
Maintainer: @jsl
Description:
Fix package names :) Last one, I swear.

yate: remove underscores from package names

---

net/kamailio-5.x/Makefile

Underscores should not be used in package base names as they're used as
semantic separators by opkg.
Description:
Fix package name.

kamailio-5.x: remove underscores from package names

---

net/rtpproxy/Makefile

Description:
Fix package names.

rtpproxy: remove underscores from package names

---

net/baresip/Makefile

Description:
Fix package naming.

baresip: remove underscores from package names

---

net/siproxd/Makefile

Underscores should not be used in package base names as they're used as
semantic separators by opkg.
Maintainer: @jsla
Description:
Hi Jiri,
Fix package names, same as the others.
Kind regards,
Seb

siproxd: remove underscores from package names

---

net/asterisk-13.x-chan-lantiq/Makefile
net/asterisk-13.x-chan-lantiq/files/default.exports

Backports chan-lantiq to LEDE 17.01.
Compile tested: lantiq xway200
Description:
Backport chan-lantiq to 17.01 now that master version builds on the bots.

asterisk13-chan-lantiq: backport to 17.01

---

net/yate/Makefile

When configure is called with '--with-mysql="$(STAGING_DIR)/usr"' it tries
to detect mysql manually instead of using mysql_config. This doesn't always
work:
```
<snip>
checking for MySQL in /var/lib/buildbot/slaves/slave-lede-builds4/i386_pentium4/build/sdk/staging_dir/target-i386_pentium4_musl/usr... no
<snip>
```
This commit changes the configure argument to '--with-mysql=yes/no'. When
'yes' is selected configure uses mysql_config and then the detection works
reliably.
```
<snip>
checking for MySQL using mysql_config... yes 10.1.32
checking whether MYSQL_OPT_RECONNECT is declared... yes
checking whether MYSQL_OPT_READ_TIMEOUT is declared... yes
checking whether MYSQL_OPT_WRITE_TIMEOUT is declared... yes
checking whether mysql_set_character_set is declared... yes
<snip>
``` …

yate: fix mysql detection

---

net/asterisk-13.x/Makefile
net/asterisk-15.x/Makefile

Description:
Hello Jiri,
Turns out the sound pack download issue is easy to fix after all. Just a one-liner :)
Kind regards,
Seb

asterisk: remove sounds cache

---

net/asterisk-13.x/Makefile
net/asterisk-15.x/Makefile

Description:
Same as in master.
Regards,
Seb

asterisk in 18.06: remove sounds cache

---

net/asterisk-13.x/Makefile

When there is no sounds cache declared the build system will not attempt to
download any sound packs or their SHA1 checksums.
This is to be preferred because:
a) the build may occur offline, causing it to fail
b) plain http is used by the build system for downloading
There is no drawback here because the standard sound packs are included in
the Asterisk source tarball already.
Compile tested: lantiq
Description:
Hello Jiri,
As there will be another 17.01 release I suggest to port this back to 17.01 as well, to make sure that there will be chan-lantiq available from the build bots. If the build bot doesn't allow fetches during the building itself, then this could …

asterisk-13.x: remove sounds cache

---

net/siproxd/Makefile
net/siproxd/files/siproxd.init

Compile tested: ar71xx/mips24kc
Run tested: ar71xx/mips24kc under LEDE 17.01.4
Description:
Hi Jiri,
This PR includes  changes I've been testing for several weeks under LEDE 17.01.4, which update `siproxd.init` to use `procd` with support for jails, and clean up the code for improved readability and robustness.
The code restructuring also (unknowingly) addressed a bug just reported by @mkuron in #329 which, together with the recent OpenWRT-18.06 branching, are prompting making this PR now. I've also asked him to review this PR.
Please review the changes and consider them for backporting to both LEDE 17.01.4 and OpenWRT-18.06 branches.
Kind regards,
Tony

siproxd: switch to procd, restructure/cleanup code, bugfix

---

net/siproxd/Makefile
net/siproxd/files/siproxd.init

Maintainer: @jslachta, @micmac1 
Compile tested: ar71xx/mips24kc
Run tested: ar71xx/mips24kc under LEDE 17.01.4
Description:
Hi Jiri, Seb,
This a straight cherry-pick of the changes as discussed in #332.
Thanks,
Tony

siproxd: backport procd switch and cleanup to openwrt-18.06

---

net/siproxd/Makefile
net/siproxd/files/siproxd.init

Maintainer: @jslachta, @micmac1 
Compile tested: ar71xx/mips24kc
Run tested: ar71xx/mips24kc under LEDE 17.01.4
Description:
Hi Jiri, Seb,
This a straight cherry-pick of the changes as discussed in #332.
Thanks,
Tony

siproxd: backport procd switch and cleanup to lede 17.01

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/350-fix-pcre-pointer-type.patch

Currently compiles fail with:
CC       libfreeswitch_la-switch_regex.lo
src/switch_regex.c: In function 'switch_regex_compile':
src/switch_regex.c:40:9: error: return from incompatible pointer type [-Werror=incompatible-pointer-types]
return pcre_compile(pattern, options, errorptr, erroroffset, tables);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:2100: recipe for target 'libfreeswitch_la-switch_regex.lo' failed
make[5]: *** [libfreeswitch_la-switch_regex.lo] Error 1
Fix cherry-picked from upstream.
Maintainer: me

freeswitch-stable: fix incompatible pointer type

---

net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/040-AST-2018-008-13.diff

Patch from upstream for AST-2018-008.
Description:
Hello Jiri,
I'll post some pull requests to get security issues fixed. Patches from upstream.
Best regards,
Seb

(for CC-15.05) asterisk-13.x: patch AST-2018-008

---

net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/060-AST-2018-008-13.diff

Patch from upstream for AST-2018-008.

(for lede-17.01) asterisk-13.x: patch AST-2018-008

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/270-fix-uclibc-iconv-in-gsmopen.patch
net/freeswitch-stable/patches/360-fix-APR_TRY_COMPILE_NO_WARNING.patch

Maintainer: me
Compile tested: ar71xx + archs
Description:
Fix apr m4 macro plus replace iconv hack in FS with nls.mk.

freeswitch-stable: fix iconv related issues

---

net/freeswitch-stable/Makefile

The sed script used on libs/unimrcp is used to set LDFLAGS using
APR_SETVAR. Since nls.mk is included there are LDFLAGS with commas. But
the macro APR_SETVAR uses commas to separate arguments, so now the
LDFLAGS are only getting partially copied.
Solve this by surrounding LDFLAGS with brackets ([...]).
Maintainer: me
Compile tested: ar71xx, archs
Description:
Fix compile failure caused by sed script.

freeswitch-stable: fix sed script

---

net/freeswitch-stable/Makefile

1. fail2ban
2. raven
3. video_filter
All three are new in FreeSWITCH 1.8.
Maintainer: me
Description:
Add modules that were added in 1.8.

freeswitch-stable: add new modules

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/020-fix-fs_cli-typo.patch

Fix a typo. Sent to upstream via Jira FS-11309.
Maintainer: me
Run tested: ar71xx
Description:
Fix fs_cli issue.

freeswitch-stable: fix garbled output in fs_cli

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/files/freeswitch.init

Sometimes freeswitch doesn't exit after receiving the SIGTERM signal.
This can be reproduced by sending SIGTERM to a freeswitch instance which
is initializing (which can take quite some time).
Instead of just giving up and exiting - leaving a hung freeswitch
process on the system - this commit adds some lines to the init script
that send SIGKILL to freeswitch in case the attempt to terminate it with
SIGTERM fails.
Maintainer: me
Run tested: ar71xx
Description:
Improve stop procedure in init script.

freeswitch-stable: add SIGKILL to init script

---

net/asterisk-chan-sccp/Makefile

Instead just include nls.mk.
Compile tested: mips24kc, archs
Run tested:  N/A
Description:
Hi Jiri,
This removes the iconv hack also from chan-sccp.
Kind regards,
Seb

asterisk-chan-sccp: remove iconv hack

---

net/asterisk-13.x/Makefile
net/asterisk-15.x/Makefile

Compile tested: archs
Run tested: don't have archs hardware
Description:
Hello Jiri,
I'm cleaning up after the fallout from the libmariadb 10.2 upgrade. Asterisk is affected and needs a bit of tweaking for the uclibc compiles.
Kind regards,
Seb

asterisk: fix iconv related build issue

---

net/kamailio-5.x/Makefile
net/kamailio-5.x/patches/140-CVE-2018-14767.patch

CVE-2018-14767: "In Kamailio before 5.0.7 and 5.1.x before 5.1.4, a
crafted SIP message with a double "To" header and an empty "To" tag
causes a segmentation fault and crash. The reason is missing input
validation in the "build_res_buf_from_sip_req" core function. This could
result in denial of service and potentially the execution of arbitrary
code."
Description:
Hi Jiri,
Fixes CVE. Patch from upstream.
Kind regards,
Seb

kamailio-5.x: add fix for CVE-2018-14767

---

net/kamailio-4.x/Makefile
net/kamailio-4.x/patches/130-CVE-2018-14767.patch

CVE-2018-14767: "In Kamailio before 5.0.7 and 5.1.x before 5.1.4, a
crafted SIP message with a double "To" header and an empty "To" tag
causes a segmentation fault and crash. The reason is missing input
validation in the "build_res_buf_from_sip_req" core function. This could
result in denial of service and potentially the execution of arbitrary
code."
Patch from upstream. Path to msg_translator.c amended.
Description:
Same patch, only had to fix the path to the source file.
Kind regards,
Seb

kamailio-4.x: add fix for CVE-2018-14767

---

net/kamailio-5.x/Makefile
net/kamailio-5.x/patches/141-CVE-2018-16657.patch

In Kamailio before 5.0.7 and 5.1.x before 5.1.4, a crafted SIP message with
an invalid Via header causes a segmentation fault and crashes Kamailio. The
reason is missing input validation in the crcitt_string_array core function
for calculating a CRC hash for To tags. (An additional error is present in
the check_via_address core function: this function also misses input
validation.) This could result in denial of service and potentially the
execution of arbitrary code.
Patch from upstream.
Description:
Hello Jiri,
Fix for a CVE that was recently announced.
Kind regards,
Seb

(master) kamailio-5.x: add fix for CVE-2018-16657

---

net/kamailio-5.x/Makefile
net/kamailio-5.x/patches/141-CVE-2018-16657.patch

In Kamailio before 5.0.7 and 5.1.x before 5.1.4, a crafted SIP message with
an invalid Via header causes a segmentation fault and crashes Kamailio. The
reason is missing input validation in the crcitt_string_array core function
for calculating a CRC hash for To tags. (An additional error is present in
the check_via_address core function: this function also misses input
validation.) This could result in denial of service and potentially the
execution of arbitrary code.
Patch from upstream.
Description:
Hello Jiri,
Same as for master.
Kind regards,
Seb

(OpenWrt 18.06) kamailio-5.x: add fix for CVE-2018-16657

---

net/kamailio-4.x/Makefile
net/kamailio-4.x/patches/131-CVE-2018-16657.patch

In Kamailio before 5.0.7 and 5.1.x before 5.1.4, a crafted SIP message with
an invalid Via header causes a segmentation fault and crashes Kamailio. The
reason is missing input validation in the crcitt_string_array core function
for calculating a CRC hash for To tags. (An additional error is present in
the check_via_address core function: this function also misses input
validation.) This could result in denial of service and potentially the
execution of arbitrary code.
Patch from upstream. File paths amended for 4.x release.
Description:
Hi Jiri,
Same as for master. Couldn't runtest on 17.01 because got no device currently running that. But …

(LEDE 17.01) kamailio-4.x: add fix for CVE-2018-16657

---

net/yate/Makefile

.. because the musl implementation doesn't seem to be fully compatible
with yate. We switched to the musl implementation in f6ad95d.
Yate has this regexp:
^([[:alpha:]][[:alnum:]]+:)?/?/?([^[:space:][:cntrl:]@]+@)?([[:alnum:]._+-]+|[[][[:xdigit:].:]+[]])(:[0-9]+)?
Given a string like
sip:012345678@11.111.11.111:5060;user=phone
musl's regexec() returns these matches:
```
index start end
0     -1    0
1     0     32   sip:012345678@11.111.11.111:5060
2     -1    -1
3     0     14   sip:012345678@
4     14    27   11.111.11.111
5     27    32   :5060
```
.. but this is what yate expects:
```
index start end
0     -1    0
1     0     32   sip:012345678@11.111.11.111:5060
2     0     4    sip:
3     4     14   012345678@
4     14    27   11.111.11.111
5     27    32   :5060
```
Fixes #378 …

yate: Revert to internal regex implementation

---

net/asterisk-opus/Makefile
net/asterisk-opus/patches/01-Makefile.patch

Add package for Opus codec support plugin. Variants for both asterisk13
and asterisk15 included.
Maintainer: nobody yet :)
Run tested: dir-825-c1, pass-through mode worked fine. Transcoding not completely sure because it maxed out my router. I called Ekiga echo test number and heard the announcement, so PCMA to Opus transcoding was fine. But during echo test I couldn't hear anything. Maybe because of my router being overloaded. Saw no errors in Asterisk debug.
Description:
Opus codec module for Asterisk. Variant build enabled.
Hello @dhewg can you check this out, please?
Regards,
Seb

asterisk-opus: new package

---

net/kamailio-5.x/Makefile
net/kamailio-5.x/patches/150-posix-awk-filter.patch

With OpenWrt default awk - so awk from busybox - the filter is broken,
causing jsonrpc calls to fail, i.e. when running "kamctl ps". Below
patch makes the filter portable. Patch was already accepted upstream.
Compile tested: mips24kc DIR-825 C1
Run tested: mips24kc DIR-825 C1
Description:
Hello Jiri,
This fixes kamctl runtime failures due to non-portable awk script.
Kind regards,
Seb

kamailio-5.x: make jsonrpc filter portable

---

net/kamailio-5.x/Makefile
net/kamailio-5.x/patches/150-posix-awk-filter.patch

Description:
Hello Jiri,
This fixes the awk issue in master. Also, I tweaked the Makefile a bit.
I plan an submitting some more pull requests for kamailio in the not too distant future (Christmas?), i.e. add procd support as well as uci config. That'll take some more testing :)
Best regards,
Seb

kamailio-5.x: fix awk issue and some tweaks

---

net/asterisk-15.x/Makefile
net/asterisk-15.x/patches/110-AST-2018-010-15.diff

```
Patch from upstream:
Summary        Remote crash vulnerability DNS SRV and NAPTR lookups
Nature of Advisory  Denial Of Service
Susceptibility    Remote Unauthenticated Sessions
Severity       Moderate
Exploits Known    No
Reported On     October 23, 2018
```
Run tested: only compile-tested; patch applies cleanly, should be OK
Description:
Fixes AST-2018-010

(master) asterisk-15.x: add patch for AST-2018-010

---

net/baresip/Makefile

Following up the discussion in pull request #388 this commit removes the
depend on libx264 and prevents baresip from linking to libx264.
baresip can still use a H.264 encoder through ffmpeg, which is the
preferred way anyway.
Description:
Prevent baresip from linking to libx264.

baresip: remove depend on libx264

---

net/kamailio-5.x/Makefile
net/rtpproxy/Makefile

Run tested: ar71xx
Description:
Hello Jiri,
I did a copy-and-paste error earlier. The hotplug scripts weren't named properly. This fixes these.
Kind regards,
Seb

rtpproxy & kamailio: fix hotplug script file names

---

net/siproxd/Makefile
net/siproxd/files/siproxd.init

**Maintainer**: @jslachta 
**Compile tested**: ar71xx, DIR-835, LEDE-17.01.5
**Run tested**: (as above) Confirmed wiki link in package metadata and capture of debug output in syslog
**CC**: @micmac1 
**Description**:
Hi Jiri, Seb,
This is a follow-up from the examples/docs/wiki discussions in https://github.com/openwrt/telephony/issues/384 and https://github.com/openwrt/telephony/pull/387, and adds a package-metadata link to the OpenWrt wiki for `siproxd`.  While troubleshooting #384 I also noticed debug output wasn't being captured to syslog, so also fixed that. Please have a look...
Best regards,
Tony

siproxd: add wiki link and fix debug log capture

---

net/freeswitch-stable/Makefile

Includes crash-fix for mod_sofia from upstream, FS-11583.
Maintainer: me
Run tested: ar71xx, dir-825c1,running FS against provider
Description:
Version bump. I have this version running on 18.06. If all is well will backport this there next weekend.
Regards,
Seb

freeswitch-stable: bump to version 1.8.4

---

libs/dahdi-tools/Makefile
libs/dahdi-tools/patches/010-fix-non-glibc-builds.patch
libs/dahdi-tools/patches/020-fix-undefined-reference-to-get_ver.patch

Run tested: ath79
Description:
Hello Jiri,
I've updated the telephony packages today. Apart from the version bumps I've also reverted some copyright changes introduced by me in the past, as it has been made clear to me that I'm actually not allowed to change OpenWrt copyright lines because I'm not affiliated with OpenWrt. I'm also not allowed to change copyright lines from other people (your's for instance). So I reset some copyright lines.
I left kamailio alone for now. They have 5.2.0 out, but I'll wait for a minor release bump and update then.
I haven't run-tested any of this yet, because currently I don't have access to a trunk release running on a router. I'll test what I can the coming weekend and ping you.
If anybody else can test any of …

dahdi-tools: version bump

---

net/asterisk-g72x/Makefile

Description:
Update to 1.4.3, includes asterisk 16 support.

asterisk-g72x: update to 1.4.3

---

libs/libsrtp2/Makefile

Upstream fixed dependency on libpcap. The lib does not link to it
anymore as it does not need it.
Description:
libsrtp2 update

libsrtp2: update to 2.2.0

---

libs/dahdi-tools/Makefile
libs/dahdi-tools/patches/010-fix-non-glibc-builds.patch

Currently builds for ARC are failing, causing follow-up breakage. It
seems that uclibc defines __GLIBC__ on the build bots.
This commit adds a test for execinfo.h to the configure script. The
result of the test is then used in xpp/xtalk/debug.c.
Run tested: not relevant, build fix
Description:
Hello Jiri,
The patch I sent earlier doesn't seem to work very well. On the build bots the ARC builds are currently failing. So they must have __GLIBC__ defined there.
I reworked the patch to explicitly check for the execinfo header. This should fix it.
Kind regards,
Seb

dahdi-tools: rework patch

---

net/asterisk-15.x/Makefile
net/asterisk-15.x/patches/110-AST-2019-001-15.diff

Remote crash vulnerability with SDP protocol violation.
Compile tested: ath79, master
Run tested: ath79, master, dir-825-c1, ran asterisk, made phone call using pjsip
Description:
Security bump. Simple patch, straightforward.
Kind regards,
Seb

asterisk-15.x: add patch for AST-2019-001

---

net/asterisk-15.x/Makefile
net/asterisk-15.x/patches/150-AST-2019-001-15.diff

Remote crash vulnerability with SDP protocol violation.
Compile tested: 18.06 ar71xx
Run tested: master on ath79, see other pull request
Description:
Same patch.

asterisk-15.x (18.06): add patch for AST-2019-001

---

net/kamailio-5.x/Makefile
net/kamailio-5.x/patches/140-redis_use_pkg-config.patch

Compile tested: ath79, master
Run tested: not needed, only compile-related
Description:
Hello Jiri,
neheb merged the libhiredis pc file fix yesterday, so the patch can be relieved of the workaround.
Kind regards,
Seb

kamailio-5.x: update hiredis patch

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/400-switch_core_media-fix-stringop-truncation.patch
net/freeswitch-stable/patches/410-mod_say_ja-fix-format-overflow.patch

Add two patches that were submitted upstream to address warnings that
occur when using gcc 8.3 (like arc does currently) which turn into
errors (-Werror).
Maintainer: me
Compile tested: arc master
Description:
Fix some gcc 8.3 warnings

freeswitch-stable: fix gcc8 warnings

---

net/freeswitch-stable/Makefile

The ffmpeg full variant does not compile on i386_pentium currently.
Disable mod_av on i386 to prevent breakage on the buildbots.
Maintainer: me

freeswitch-stable: disable mod_av on i386

---

net/asterisk-16.x/Makefile
net/asterisk-16.x/files/asterisk.default
net/asterisk-16.x/files/asterisk.init
net/asterisk-16.x/patches/001-disable-semaphores-check.patch
net/asterisk-16.x/patches/002-configure-fix-detection-of-re-entrant-resolver-funct.patch
net/asterisk-16.x/patches/030-GNU-GLOB-exts-only-on-glibc.patch
net/asterisk-16.x/patches/053-musl-mutex-init.patch
net/asterisk-16.x/patches/056-fix-check_expr2-build.patch
net/asterisk-16.x/patches/100-build-reproducibly.patch
net/asterisk-16.x/patches/110-fix-astmm.patch
net/asterisk-16.x/patches/120-loader.patch
net/asterisk-16.x/patches/130-eventfd.patch

Compile tested: master, ath79 (musl) + arc (uclibc)
Description:
Hello all,
This is not ready for merging yet. There is a problem with segmentation faults when the module loader starts. I've had help from the [musl list](https://www.openwall.com/lists/musl/2019/02/28/4) and raised as issue for it [upstream](https://issues.asterisk.org/jira/browse/ASTERISK-28319).
According to [asterisk wiki](https://issues.asterisk.org/jira/browse/ASTERISK-28319) Asterisk 15 will be EOL 2019-10-03, so getting Asterisk 16 in would be nice. Not to mention that 16 is an LTS release. But before this can be merged something needs to be done regarding the segmentation fault.
Kind regards,
Seb

asterisk-16: new package

---

libs/pjproject/Makefile
libs/pjproject/patches/210-outgoing_connected_line_method_update.patch
libs/pjproject/patches/220-Fixed-2172-Avoid-double-reference-counter-decrements.patch
libs/pjproject/patches/230-Re-2176-Removed-pop_freelist-push_freelist-after-rem.patch
net/asterisk-g72x/Makefile
net/asterisk-opus/Makefile

Compile tested: arm/master
Run tested: arm/master
Description:
It seems asterisk gets no testing at all with musl, so I had to add two patches to get it working in the first place. But this exact version submitted here is running on my openwrt cubieboard2 for a few weeks now - and it works for me.
With this new package I chose to not add all the deprecated modules. With the idea that we can add those if there's demand for it.
* Add two pjproject patches, taken from the asterisk 16 tree
* Add the new v16 LTS release
* Add asterisk 16 variants of g72x and opus
Thanks!

Asterisk 16 additions

---

net/asterisk-16.x-chan-lantiq/Makefile
net/asterisk-16.x-chan-lantiq/patches/01-Use-ast_malloc-and-ast_free-instead-of-malloc-and-free.patch

Patch from upstream pull request
(https://github.com/kochstefan/asterisk_channel_lantiq/pull/3).
Compile tested: xrx200
Description:
Hello Jiri,
When I swapped the astmm patch with the one from Timo Teräs I didn't rerun the compile tests of the external plugins. chan-lantiq fails.
astmm.h:160:2: error: "Do_not_use_malloc__use_ast_malloc" undeclared (first use in this function)
Thanks to @arnysch for the patch!
Kind regards,
Seb

asterisk-16.x-chan-lantiq: add compile fix

---

net/asterisk-chan-sccp/Makefile
net/asterisk-chan-sccp/patches/110-fix-compile-with-gcc8.patch

Patch applied upstream. Fixes compiles for arc targets, which already
use new gcc8 toolchain.
Compile tested: ath79, archs
Run tested: N/A (compile fix only)
Description:
Hello Jiri,
I checked for compile failures on the build bots. Only found sccp not compiling (on ARC, which uses new toolchain already). The rest of the packages (including chan-lantiq) compile fine.
Patch was applied upstream by Diederik.
Kind regards,
Seb

asterisk-chan-sccp: fix gcc8 compiles

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/files/freeswitch.init

- added trailing '--' to logger to make it foolproof
- the script now checks if user and group exist
- directory creation is now done via awk script (more robust)
Maintainer: me
Run tested: ath79, master, checked if logging, user/group check and dir creation work
Description:
While working on asterisk init I saw some things that could also be applied to fs init.

freeswitch-stable: init script update

---

libs/dahdi-linux/Makefile
libs/dahdi-linux/patches/003-fix-oslec-build.patch
libs/dahdi-linux/patches/100-add-support-for-hfc-s-pci.patch

This commit goes back from using a git checkout to using a regular
upstream tarball. Version bumped to 3.0.0 which works with kernels
equal to or greater than 4.15. Patches refreshed.
resolves #427
Compile tested: ath79 against kernel 4.19.50
Run tested: don't have the hardware
Description:
Hi Jiri,
Petr sent a patch to openwrt-devel earlier today ([here](https://lists.infradead.org/pipermail/openwrt-devel/2019-June/017666.html)) that switches all but two targets to 4.19. Once this gets merged would be the right time to commit this bump PR.
I'll ping again once this happens.
Kind regards,
Seb

dahdi-linux: bump to 3.0.0

---

net/asterisk-13.x/Makefile
net/asterisk-16.x/Makefile

Description:
Hi Jiri,
chan-phone has fallen victim to the kernel upgrade :) They removed the telephony headers it requires (I think they already removed them in 4.17 - which OpenWrt never used as far as I know).
The telephony headers will not come back, so chan-phone can just be dropped. I imagine nobody uses chan-phone anyway.
Kind regards,
Seb

Asterisk: remove chan-phone

---

net/baresip/Makefile

Since OpenWrt commit e82a4d9cfb ("config: regenerate *_shipped sources")
a few recursive dependencies have been discovered that were not visible
before.
$ make menuconfig
tmp/.config-package.in:103098:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:103098: symbol PACKAGE_baresip-mod-pulse depends on PACKAGE_baresip-mod-pulse
tmp/.config-package.in:121863:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:121863: symbol PACKAGE_pulseaudio-profiles depends on PACKAGE_pulseaudio-profiles
tmp/.config-package.in:121878:error: …

baresip: fix recursive dependency

---

net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/110-AST-2019-002-13.diff
net/asterisk-13.x/patches/120-AST-2019-003-13.diff
net/asterisk-16.x/Makefile
net/asterisk-16.x/patches/140-AST-2019-002-16.diff
net/asterisk-16.x/patches/150-AST-2019-003-16.diff

Description:
CVE fixes. This if for master and the last of the PRs.
Small reminder, it'd be great if we could get rid of asterisk 13. CVE-patching the asterisk packages is double the work always :-)

asterisk-1{3,6}.x: fix AST-2019-002 & AST-2019-003

---

net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/110-AST-2019-002-13.diff
net/asterisk-13.x/patches/120-AST-2019-003-13.diff
net/asterisk-16.x/Makefile
net/asterisk-16.x/patches/140-AST-2019-002-16.diff
net/asterisk-16.x/patches/150-AST-2019-003-16.diff

Compile tested: ath79, master (same Asterisk versions used in 19.07)
Description:
CVE fixes

(for 19.07) asterisk-1{3,6}.x: fix AST-2019-002 & AST-2019-003

---

net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/080-AST-2019-003-13.diff

https://downloads.asterisk.org/pub/security/AST-2019-003.html
Compile tested: ar71xx 17.01
Description:
Hi Jiri,
I'm raising PRs for AST-2019-002 and AST-2019-003, released today. They're both remote crash vulns, but only concern in-dialog messaging, severity is low/minor according to upstream.
While they affect 13, 15 and 16, AST-2019-002 seems to not be applicable to versions which don't contain at least commit "bridge_softmix: Forward TEXT frames". The function "check_content_type_any_text()" or "check_content_type_in_dialog()" simply don't exist then. So in this case I'll only add the upstream patch for AST-2019-003.
Regards,
Seb

(for 17.01) asterisk-13.x: fix AST-2019-003

---

net/asterisk-16.x/Makefile

Recently liblua5.3 was added in the base repo. When both default liblua
and liblua5.3 are staged, asterisk will prefer the latter. But then the
dependency is wrong, because the linked-to lib is in liblua5.3.
This commit upgrades the dependency from liblua to liblua5.3.
Resolves #441.
Compile tested: ath79, master
Run tested: N/A, just a dep fix
Description:
Hi Jiri,
I hope you're enjoying the summer!
Kind regards,
Seb

asterisk-16.x: upgrade pbx-lua dep to liblua5.3

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/140-libvpx-cross.patch

Maintainer: me
Compile tested: x86_64, master
Description:
FS 1.10 includes a new utlity, this PR adds it. Also it's visible on the build bots that libvpx bombs, so this PR addresses that. The latter only affects x86_64 on the build bots, because libvpx support is default-disabled for all other targets.
Not bumping revision because it's not needed for these two changes.

freeswitch-stable: a fix and a new utility

---

net/freeswitch-stable/Makefile

Maintainer: me
Compile tested: master + 18.06, ath79
Run tested: 18.06, ar71xx
Description:
First minor version bump. Currently running this, seems fine. Will leave it for a few days. If all well will backport this to 19.07.

freeswitch-stable: bump to 1.10.1

---

net/freeswitch-stable/Makefile

It's better to rely on qstrip than to look for certain quotes.
Maintainer: me
Run tested: N/A, just a Makefile update
Description:
Wanted to do this for a long time, but kept forgetting about it.

freeswitch-stable: use qstrip

---

net/baresip/Makefile

Since OpenWrt commit e82a4d9cfb ("config: regenerate *_shipped sources")
a few recursive dependencies have been discovered that were not visible
before.
$ make menuconfig
tmp/.config-package.in:103098:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:103098: symbol PACKAGE_baresip-mod-pulse depends on PACKAGE_baresip-mod-pulse
tmp/.config-package.in:121863:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:121863: symbol PACKAGE_pulseaudio-profiles depends on PACKAGE_pulseaudio-profiles
tmp/.config-package.in:121878:error: …

[19.07] baresip: fix recursive dependency

---

net/asterisk-16.x/Makefile
net/asterisk-16.x/patches/160-AST-2019-004-16.patch

Add patch for a remote crash vulnerability. Crash can occur when
negotiating for T.38 with a declined stream.
CVE-2019-15297
Compile tested: master (uses same Asterisk version)
Run tested: master
Description:
Same CVE fix as for master

[19.07] asterisk-16.x: add patch for AST-2019-004

---

net/asterisk-16.x/Makefile
net/asterisk-16.x/patches/160-AST-2019-004-16.patch

Add patch for a remote crash vulnerability. Crash can occur when
negotiating for T.38 with a declined stream.
CVE-2019-15297
Compile tested: master, ath79
Run tested: master, ath79, dlink dir-825-c1 (note: this is for T.38 handling in pjsip which I didn't test. I used pjsip for test calls which worked fine. Don't have faxing setup. Anyway, should be OK.
Description:
CVE fix. Will also (try to) backport this to releases.
Note: there's also AST-2019-005, but it doesn't affect us. That vuln was introduced in 13.28.0 and 16.5.0, which we never used.

asterisk-16.x: add patch for AST-2019-004

---

net/asterisk-15.x/Makefile
net/asterisk-15.x/patches/120-AST-2018-008-15.diff
net/asterisk-15.x/patches/150-AST-2019-001-15.diff
net/asterisk-15.x/patches/160-AST-2019-003-15.diff
net/asterisk-15.x/patches/170-AST-2019-004-15.patch

Add patch for a remote crash vulnerability. Crash can occur when
negotiating for T.38 with a declined stream.
CVE-2019-15297
Refreshed some other patches.
Compile tested: 18.06 ar71xx
Run tested: master
Description:
Same CVE fix for 18.06. Had to fiddle with one patch hunk where the next line in our 15.x version returns a different result than in the patch. Should be fine. Refreshed some other patches.

[18.06] asterisk-15.x: add patch for AST-2019-004

---

net/freeswitch-stable/Makefile

This warning is not relevant anymore.
Maintainer: me
Description:
Remove obsolete comment.

net/freeswitch-stable: remove old warning

---

libs/bcg729/Makefile
libs/bcg729/patches/01-install-pkg-config-file.patch

Patch from upstream.
With the .pc file available we can drop a hack in rtpproxy's Makefile.
Run tested: N/A, no runtime change
Description:
Add .pc file.

bcg729: add pkg-config file

---

net/pcapsipdump/Makefile

The last official release is quite old. But pcapsipdump's trunk has seen
a steady stream of fixes and improvements. This commit updates the
package to a current SVN snapshot.
MAKE_FLAGS is simplified. The deleted ARGS are provided by OpenWrt
buildroot, no need to specify them again. All that is needed is LIBS.
Compile tested: x86_64 native, ath79 master on OpenWrt
Run tested: dlink router, mips BE
Description:
Hi Jiri,
When working on upgrading this I ran into some problems. There was a tiny compile issue and an endian problem. But the pcapsipdump maintainer was very helpful (and very quick) and now fixes are upstream.
Kind regards,
Seb

pcapsipdump: update to trunk snapshot

---

net/pcapsipdump/Makefile
net/pcapsipdump/patches/01-use-libc-strlcpy-if-available-v2.patch

When libbsd is available in staging it will be picked up by pcapsipdump
during the compile. The binary will link to libbsd, causing an
additional dependency. Currently the builds on the bots are failing
because of this.
The only function pcapsipdump is using from libbsd is strlcpy(). This
function is also provided by uClibc as well as musl.
Attached patch adds a detection mechanism that checks whether libc
provides strlcpy(). This way the dependency on libbsd is only required if
building against a libc which doesn't package strlcpy(), like glibc.
DEPENDS are updated to reflect that.
Compile tested: ath79 master against musl, arc770 master against uClibc, x86_64 native compile …

pcapsipdump: fix missing libbsd depend

---

net/kamailio-5.x/Makefile

From upstream release notes:
Six new modules:
- app_lua_sr – old Lua API before introduction of KEMI
- lost – HELD (RFC6155) and LOST (RFC5222) location-based routing
- kemix – KEMI specific extensions
- rtp_media_server – embedded RTP and media processing
functionalities for Kamailio (like playing media or bridging in a
B2BUA manner, includes support for different codecs, including Opus)
- secfilter – filters to allow/block using whitelists/blacklist based
on user agents, IP addresses, countries, domains and users
- xhttp_prom – generates suitable metrics for a Prometheus monitoring
platform, answering to Prometheus pull requests
Additionally this removes libxml2 dependency from modules, because base
kamailio package already depends on it.
Signed-off-by: Sebastian Kemper …

kamailio-5.x: add new modules + cleanup

---

net/kamailio-5.x/Makefile

menuconfig is currently showing warnings for kamailio:
WARNING: Makefile 'package/feeds/telephony/kamailio-5.x/Makefile' has a dependency on 'bcunit', which does not exist
WARNING: Makefile 'package/feeds/telephony/kamailio-5.x/Makefile' has a dependency on 'mediastreamer2', which does not exist
WARNING: Makefile 'package/feeds/telephony/kamailio-5.x/Makefile' has a dependency on 'ortp', which does not exist
This commit removes the non-existent dependencies to clear the warnings.
Description:
Thanks to @hnyman for mentioning the _warnings_ in #480

kamailio-5.x: remove rtp_media_server package

---

net/asterisk-16.x/Makefile

There were problems in the past with OpenWrt's libxml2 package (also
it's host package). This led to quite a few workarounds in the asterisk
Makefile.
Recent changes in the libxml2 package have cleared this up.
1. a proper xml2-config file is now installed by both libxml2 and
libxml2/host
2. xml2-config is now installed with a host triplet prefix (e.g.
"mips-openwrt-linux-xml2-config" for libxml2 and
"x86_64-pc-linux-gnu-xml2-config" for libxml2/host), additionally
these tools get a symbolic link to xml2-config
That means that now OpenWrt's libxml2 can be properly detected and the
workarounds are no longer required.
This commit also removes an explicit dependency on libxml2 from
res-calendar-caldav. The base package already depends on libxml2, hence
the dependency is implicit. …

asterisk-16.x: remove libxml2 hacks

---

libs/pjproject/Makefile
libs/pjproject/patches/0006-fix-pkg_config-file.patch

The .pc file uses hard-coded paths:
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib
includedir=/usr/include
It also pushes "-I/usr/include" into CFLAGS. This commit amends all of
that.
Resolve: #483
Run tested: N/A, no run-time change
Description:
Thanks @neheb for reporting!

pjproject: fix pkg-config file

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/400-CVE-2019-9232_9325_9371_9433.patch

Patch taken from Debian Buster, fixes:
CVE-2019-9232
CVE-2019-9325
CVE-2019-9371
CVE-2019-9433
Maintainer: me
Run tested: N/A, VPX is for video calls, I don't do video calls
Description:
CVE fixes for included libvpx. Patch copied from Debian Buster.
Ping libvpx maintainer @luizluca as maybe interesting for packages repo, too.

freeswitch-stable: patch CVEs in included libvpx

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/390-t38-reinvite-488-fix.patch
net/freeswitch-stable/patches/400-CVE-2019-9232_9325_9371_9433.patch

Maintainer: me
Run tested: T38 patch on x86_64, VPX patch not tested as I don't do video calls.
Description:
libvpx CVE patch from Debian + tiny T38 patch + warning removal.

(19.07) freeswitch-stable: fix libvpx CVEs + T38 patch

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/430-CVE-2019-9232_9325_9433.patch

Patch taken from Debian Stretch, fixes:
CVE-2019-9232
CVE-2019-9325
CVE-2019-9433
Maintainer: me
Compile tested: x86_64 18.06
Run tested: N/A, libvpx is used for video calls, which I don't use.
Description:
Fixes libvpx CVEs. Patch taken from Debian Stretch. Debian didn't included a fix for CVE-2019-9371 in Stretch stating that it's a minor issue, see [here](https://security-tracker.debian.org/tracker/CVE-2019-9371).

(18.06) freeswitch-stable: patch CVEs in included libvpx

---

net/asterisk-16.x/Makefile
net/asterisk-16.x/patches/170-AST-2019-006-16.diff
net/asterisk-16.x/patches/180-AST-2019-007-16.diff

https://downloads.asterisk.org/pub/security/AST-2019-006.html
https://downloads.asterisk.org/pub/security/AST-2019-007.html
Compile tested: 19.07, ath79
Run tested: N/A, upstream security fixes, should be OK
Description:
Fix two security issues with patches from upstream.

[19.07] asterisk-16.x: add fixes for AST-2019-006 and 007

---

net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/090-AST-2019-006-13.diff
net/asterisk-13.x/patches/100-AST-2019-007-13.diff
net/asterisk-13.x/patches/110-AST-2019-008-13.diff

https://downloads.asterisk.org/pub/security/AST-2019-006.html
https://downloads.asterisk.org/pub/security/AST-2019-007.html
https://downloads.asterisk.org/pub/security/AST-2019-008.html
Compile tested: I tried to compile on 17.01, but menuconfig filed (unrelated to these patches). I think on the build bots this will be OK. Patches applied fine.
Description:
Security patches from upstream.

[17.01] asterisk-13.x: add fixes for AST-2019-006, 007 & 008

---

net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/140-AST-2019-006-13.diff
net/asterisk-13.x/patches/150-AST-2019-007-13.diff
net/asterisk-13.x/patches/160-AST-2019-008-13.diff
net/asterisk-15.x/Makefile
net/asterisk-15.x/patches/180-AST-2019-006-16.diff
net/asterisk-15.x/patches/190-AST-2019-007-16.diff

Compile tested: 18.06 ar71xx
Run tested: N/A, upstream security patches, should be OK
Description:
Fixes security issues with upstream patches.

[18.06] asterisk-1{3,5}.x: add fixes for AST-2019-006 and 007 (and 008)

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/040-gentls_cert_update_message_digest.patch

gentls_cert generates certificates that are deemed too weak by Debian's
OpenSSL (on Buster and up). This patch upgrades the message digest to
SHA256 to address this.
See patch for details. Sent upstream ([1]).
[1] https://github.com/signalwire/freeswitch/pull/126
Maintainer: me
Description:
Upgrade weak message digest on certificate generation.

freeswitch-stable: fix weak md in gentls_cert

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/040-gentls_cert_update_message_digest.patch

gentls_cert generates certificates that are deemed too weak by Debian's
OpenSSL (on Buster and up). This patch upgrades the message digest to
SHA256 to address this.
See patch for details. Sent upstream ([1]).
[1] https://github.com/signalwire/freeswitch/pull/126
Maintainer: me
Description:
Cherry-picked from master.

[19.07] freeswitch-stable: fix weak md in gentls_cert

---

net/asterisk-16.x/Makefile
net/asterisk-16.x/patches/056-fix-check_expr2-build.patch

CFLAGS aren't used when compiling objects for check_expr2. This commits
adds the flags, which fixes the compilation when PKG_ASLR_PIE is
enabled. Note: The STANDALONE define is removed because it is already
defined in _ASTCFLAGS.
Fixes #502
Run tested: ath79 19.07, copied over the check_expr2 executable and checked a file from the tests directory.
Description:
Fix ASLR PIE build fail
Hi Jiri, happy new year! :)

asterisk-16.x: fix compile with PKG_ASLR_PIE

---

net/freeswitch-stable/Makefile

libpq's pkg-config file is currently broken. Use pg_config instead.
Maintainer: me
Run tested: N/A, this doesn't affect the package.
Description:
Fix build on the bots.

freeswitch-stable: use pg_config for now

---

net/asterisk-16.x/Makefile
net/asterisk-16.x/patches/056-fix-check_expr2-build.patch

Compile tested: Turris Omnia, mvebu (cortex-a9), OpenWrt 19.07
Description:
As requested in #502, I would like to have it fixed in OpenWrt 19.07 as well. 
____
CFLAGS aren't used when compiling objects for check_expr2. This commits
adds the flags, which fixes the compilation when PKG_ASLR_PIE is
enabled. Note: The STANDALONE define is removed because it is already
defined in _ASTCFLAGS.
(cherry picked from commit 357949967f330ae1e6d199d1c362f2666de82c43)
____
Patch from @micmac1 was [accepted](https://gerrit.asterisk.org/c/asterisk/+/13874) and it is part of 16.9.0 release.

[19.07] asterisk-16.x: fix compile with PKG_ASLR_PIE

---

net/asterisk-16.x/patches/056-fix-check_expr2-build.patch

I'd like to apologize, I am not sure how this could happen as previously I have tested and even to be sure refreshed that patch before sending pull request.
Fixes: https://github.com/openwrt/telephony/pull/505#issuecomment-596143084

asterisk-16.x: 056-fix-check_expr2-build.patch - rebase

---

libs/dahdi-linux/Makefile
libs/dahdi-linux/patches/100-add-support-for-hfc-s-pci.patch
libs/dahdi-linux/patches/120-pci-header.patch

This commit provides compatibility with kernel 5.4.
Except for the version bump this commit updates the HFC-S PCI driver to
not rely on the macro "dahdi_pci_module" anymore, because it has been
removed upstream in commit 4af6f69.
Also, a patch is added that makes the include of "<linux/pci-aspm.h>"
conditional on the kernel version, because starting with kernel 5.4 this
header has been removed and its contents merged into "pci.h".
Run tested: N/A, don't have the hardware for it
Description:
Hi Jiri,
Some targets were upgraded to kernel 5.4. For these targets most of telephony feed is currently failing, because dahdi-linux won't compile …

dahdi-linux: bump to version 3.1.0

---

net/freeswitch-stable/Makefile

The libpq pkg-config file has been fixed in packages, so we can revert
the commit that introduced the workaround.
Maintainer: me
Compile tested: x86_64 master
Run tested: No runtime impact
Description:
Hi all,
This reverts the previous commit, as the libpq pc file has been finally fixed in packages.
Regards,
Seb

freeswitch-stable: revert libpq pc file workaround

---

net/freeswitch-stable/Makefile

Remove the opencv module from freeswitch-stable. The module has been marked BROKEN already for some time, and currently it causes a dependency error in OpenWrt config, as the opencv package itself was removed from the packages feed. 
No increase of PKG_RELEASE as removal of a broken module from Makefile does not trigger any changes for the other components.
Current error:
```
perus@ub1910:/Openwrt/r7800$ make defconfig
WARNING: Makefile 'package/feeds/telephony/freeswitch-stable/Makefile' has a dependency on 'opencv', which does not exist
#
#
```

freeswitch-stable: remove opencv module

---

net/asterisk-16.x/Makefile
net/asterisk-16.x/files/asterisk.init

Currently the init script creates "/var/lib/asterisk/keys". But the
default keys directory is actually "/usr/share/asterisk/keys".
This commit amends the init script.
Resolves #512
Compile tested: N/A (just a script change)
Run tested: 19.07.01, installed asterisk from mirrors, changed the directory in init script, ran it.
```
* Directories
-------------
Configuration file:          /etc/asterisk/asterisk.conf
Configuration directory:     /etc/asterisk
Module directory:            /usr/lib/asterisk/modules
Spool directory:             /var/spool/asterisk
Log directory:               /var/log/asterisk
Run/Sockets directory:       /var/run/asterisk
PID file: …
```

[openwrt-19.07] asterisk-16.x: update keys directory in init script

---

net/kamailio-5.x/Makefile

This PR updates kamailio to version 5.3.3.
Within this PR the python support is removed, since
the python 2.x support is removed and app-python3 is not
ready yet.
Signed-off-by: Jiri Slachta <jiri@slachta.eu>
Compile tested: ar9xxx, x86 - master 
Run tested: ar9xxx, x86 - master 
Description:
This PR updates kamailio to version 5.3.3.
Within this PR the python support is removed, sinceThis PR updates kamailio to version 5.3.3.
Within this PR the python support is removed, since
the python 2.x support is removed and app-python3 is not
ready yet.

kamailio-5.x: update to 5.3.3

---

.circleci/Dockerfile
.circleci/README
.circleci/config.yml

**Description:**
This adds [CircleCI](https://circleci.com/) from [packages repository](https://github.com/openwrt/packages) in the same state, which is there. Fixes #442 
It will give you an opinion to avoid, for example, mistakes with broken patches and provides you insights that it is compiled against the ath79 target. It will also check that each contributor has proper Signed-off-by and that the commit message starts with the prefix of the package name.
The CircleCI is being used in packages and luci repositories. There is also a possibility to use [Travis CI](https://travis-ci.org/), which is also free for open source projects, but if I remember correctly there were some false-positives, but it's up to you. I can add it as well as I am using it for packages. As if you are going to …

build: Add CircleCI

---

.circleci/config.yml

We like to use "kamailio-5.x:" and "asterisk-16.x:" in commit message
subject lines. So relax the regex for it to allow the dots.
Closes #442 
Compile tested: N/A, tested the regex locally
Run tested: N/A, not a package
Description:
Hi Jiri,
As discussed in #442 this relaxes the circleci regex a bit.
Kind regards,
Seb

circleci: allow dots in subject line

---

.circleci/config.yml

Currently CI doesn't work, because the dependencies from the packages
repo are not available.
<snip>
WARNING: No feed for package 'libopenldap' found
WARNING: No feed for package 'libidn2' found
WARNING: No feed for package 'libssh2' found
<snip>
This commit adds the packages repo.
Description:
Hi Jiri,
CI is missing the packages repo. Need to add it for our deps.
Kind regards,
Seb

circleci: fetch packages repo

---

net/kamailio-5.x/Makefile
net/kamailio-5.x/patches/150-python3-cross-compile.patch

Compile tested: ath79 master + x86_64 master
Run tested: ath79 openwrt-19.07, tested with asterisk and one phone registering to it via kamailio, the other directly. All OK, calls fine. Also checked kamctl works (listing DB, removing entry, adding entry).
Description:
Hi Jiri,
While checking into Python3 I saw that Alpine sets up the build a bit differently. I like it a lot more the way they do it. I know they're not cross-compiling like us, but replicating their setup works fine for us. Like this we can also remove the manual "make" calls, which is nice.
With regards to the Python 3 module. It builds fine, but I wasn't able to run-test it because I ran out of space when trying to install python3-light :D But I'm pretty sure it's fine.
There are some additional …

kamailio-5.x: update build setup and add Python 3 module

---

net/kamailio-5.x/Makefile

Since recent commit 60ea8ff OpenWrt flags are added to CC_EXTRA_OPTS
instead of CFLAGS, allowing upstream flags to pass into our builds.
Upstream passes "-funroll-loops", which increases package sizes
significantly.
Example mips:
kamailio5_5.3.3-1_mips_24kc.ipk: 1019K
kamailio5_5.3.3-2_mips_24kc.ipk: 1,4M
This commit removes "-funroll-loops", reducing the size to previous
level.
kamailio5_5.3.3-2_mips_24kc.ipk: 1021K
Run tested: ath79 19.07
Description:
Hi Jiri,
This is a follow-up, because I saw a pretty astonishing size increase.
I don't know if "-funroll-loops" makes kamailio faster. But I think we want to keep it as slim as possible.
Kind regards, …

kamailio-5.x: remove "-funroll-loops"

---

libs/dahdi-linux/Makefile
libs/dahdi-linux/patches/130-DAHLIN-371-pld-linux-math64.patch

On some 32 bit targets dahdi-linux currently fails to build.
Examples:
ERROR: "__divdi3" [/builder/shared-workdir/build/sdk/build_dir/target-powerpc_8540_musl/linux-mpc85xx_generic/dahdi-linux-3.1.0/drivers/dahdi/xpp/xpp_usb.ko] undefined!
ERROR: "__udivdi3" [/builder/shared-workdir/build/sdk/build_dir/target-powerpc_8540_musl/linux-mpc85xx_generic/dahdi-linux-3.1.0/drivers/dahdi/xpp/xpp_usb.ko] undefined!
ERROR: "__moddi3" [/builder/shared-workdir/build/sdk/build_dir/target-powerpc_8540_musl/linux-mpc85xx_generic/dahdi-linux-3.1.0/drivers/dahdi/xpp/xpp.ko] undefined!
ERROR: "__divdi3" [/builder/shared-workdir/build/sdk/build_dir/target-powerpc_8540_musl/linux-mpc85xx_generic/dahdi-linux-3.1.0/drivers/dahdi/xpp/xpp.ko] undefined!
or
ERROR: "__aeabi_ldivmod" …

dahdi-linux: add patch to fix 32bit targets

---

net/rtpengine/Makefile
net/rtpengine/files/rtpengine-recording.conf
net/rtpengine/files/rtpengine-recording.init
net/rtpengine/files/rtpengine.conf
net/rtpengine/files/rtpengine.hotplug
net/rtpengine/files/rtpengine.init
net/rtpengine/patches/01-cflags.patch
net/rtpengine/patches/02-kernel-include.patch
net/rtpengine/patches/03-uclibc-getloadavg.patch

Maintainer: me
Compile tested: arc770, ath79 (all master)
Run tested: ath79 19.07 (didn't try kernel module, didn't try kamailio with it either yet)
Description:
Hi @jslachta, everbody,
This was requested on [forum](https://forum.openwrt.org/t/feature-request-rtpengine-as-a-new-package-in-network-telephony/46972). Did not see the post until yesterday.
We already have the corresponding kamailio module available. rtpengine looks like a powerful proxy. Nice to have I think.
One dep wasn't available: json-glib. I added it here, but this should go to packages. I saw that @mhei sent a pull request adding cmake support to json-glib maintainers in the past, due to lack of meson in OpenWrt. But we have meson now, so there's no problem anymore.
If anybody would like to try this and could report …

rtpengine: new package

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/files/freeswitch.conf
net/freeswitch-stable/files/freeswitch.init

This is in response to a posting on oss-security ([1]).
This commit removes the ability to choose a user/group via
/etc/config/freeswitch. This makes the init script simpler. If anybody
wants to play around with the user/group then it's up to them to fix the
permissions.
The complex awk script is deleted and basically replaced by two
for-loops. The first loop creates /var/lib/freeswitch and
/var/run/freeswitch and chowns them to the user freeswitch, in case they
don't exist already.
The second loop checks if the other directories (either default or
specified by the user) exist. If any directory is missing it uses "su"
to create that directory as user "freeswitch".
The reasoning behind this is that a) this works for the defaults
(example: "/tmp/freeswitch/db") and b) the user can specify …

freeswitch-stable: improve init script

---

net/freeswitch-stable/patches/400-disable-sofia-sip-tests.patch

Upstream commit [2dced93 "[sofia-sip] Build internal tests"](https://github.com/signalwire/freeswitch/commit/2dced93d94ce4be86c57451ee842afbf435749aa) enabled the
building of tests. One of them causes build failures on the build bots:
```
Making all in s2check
make[11]: Entering directory '/builder/shared-workdir/build/sdk/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/freeswitch-1.10.3.-release/libs/sofia-sip/s2check'
COMPILE s2tcase.o
s2tcase.c: In function 's2_tcase_add_test':
s2tcase.c:60:27: error: passing argument 2 of '_tcase_add_test' from incompatible pointer type [-Werror=incompatible-pointer-types]
_tcase_add_test(tc, tf, name, signo, 0, start, end);
^~
In file included from s2tcase.c:35:
/builder/shared-workdir/build/sdk/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_e …
```

freeswitch-stable: disable sofia-sip tests

---

net/rtpengine/Makefile
net/rtpengine/patches/04-prevent-systemd-detection.patch

lib/lib.Makefile looks for libsystemd and dpkg-buildflags. These are not
available in OpenWrt, but they could be picked up from the build host.
This commit extends 01-cflags.patch a bit to prevent that.
Maintainer: me
Run tested: no runtime-change
Description:
Hi all,
Saw this going wrong on one build bot ("truecz-dock-01"). I'm betting it has dpkg-buildflags installed which introduces some host system flags into the build. The commit also prevents libsystemd detection, as a precautionary measure.
Kind regards,
Seb

rtpengine: prevent picking up host system flags

---

net/rtpengine/Makefile
net/rtpengine/patches/01-cflags.patch

Maintainer: me
Run tested: I gave this a quick spin on 19.07.
Description:
Hi all,
This updates the CFLAGS patch a bit. I think it's better this way. The second commit contains a workaround for a sporadic build failure.
No size increases. No big changes anyway.
Kind regards,
Seb

rtpengine: build fix and patch improvement

---

net/asterisk-chan-dongle/Makefile
net/asterisk-chan-dongle/patches/200-fix-iconv-detection.patch
net/asterisk-chan-dongle/patches/300-use-openwrt-flags.patch

Bump dongle plugin to latest git revision. PKG_SOURCE_SUBDIR and
PKG_BUILD_DIR are removed because defaults are fine. PKG_VERSION is
replaced by PKG_SOURCE_DATE, which is in line with OpenWrt
recommendation.
Soft deps are removed as per request in issue #536.
iconv handling is updated. Upstream now lets us specify the include
directory, so that makes the patch simpler. The iconv lib detection is
also updated so that it never picks the libc iconv. This way we get the
same iconv handling independent of the libc in use. Now it'll be always
iconv-stub or iconv-full.
libsqlite3 dep is made explicit. There was always a dep on it, but it
was implicit via asterisk. When the dep is made explicit, the dongle
package picks up on the sqlite3 ABI_VERSION, which is nice.
Signed-off-by: Sebastian Kemper …

asterisk-chan-dongle: bump + cleanup

---

net/freeswitch/patches/410-rayo-gcc10.patch

Raised issue upstream ([1]). For now let's add this workaround.
[1] https://github.com/signalwire/freeswitch/issues/742
Maintainer: me 
Compile tested: master
Run tested:
Description:

freeswitch: mod-rayo not compiling with gcc-10

---

net/rtpengine/Makefile

Needed for the glib2 update in the packages feed.

rtpengine: add nls.mk

---

net/freeswitch/Makefile

libjpeg was replaced by libjpeg-turbo in packages repo.
Maintainer: me
Description:

freeswitch: update libjpeg deps

---

net/baresip/Makefile
net/baresip/patches/010-openssl-deprecated.patch

baresip: fix compilation without deprecated OpenSSL APIs

---

libs/dahdi-tools/Makefile

This works around the build failure with gcc-10 until there is a patch
for dahdi-tools that is reviewed and acknowledged by upstream.
Close #542 
Maintainer: @VittGam
Description:

dahdi-tools: add -fcommon workaround for gcc10

---

net/rtpengine/Makefile
net/rtpengine/patches/200-openssl-deprecated.patch

rtpengine: fix compilation without deprecated OpenSSL APIs

---

libs/spandsp3/Makefile
libs/spandsp3/patches/01-spandsp3-pkg-config.patch

This commit adds an updated spandsp library. This is not a drop-in
replacement for the "old" spandsp library. Applications that want to use
it need to be updated a bit, according to upstream info [1].
In an effort to not cause any problems for OpenWrt, this package
installs the library and headers in the staging directory into
non-standard paths:
Library: $(STAGING_DIR/usr/lib/spandsp3/lib
Headers: $(STAGING_DIR/usr/lib/spandsp3/include
This way they are hidden aways from all normal users (like asterisk,
baresip etc.) and won't interfere.
To use the new spandsp library users can look for the spandsp3
pkg-config file (the regular spandsp installs spandsp.pc, this package
installs spandsp3.pc). This should be enough. The first such user will
likely be the freeswitch package, once it gets …

spandsp3: new package

---

libs/libks/Makefile
libs/libks/patches/05-openssl-deprecated.patch

libks: fix compilation without deprecated OpenSSL APIs

---

net/rtpengine/Makefile

Minor version bump. This also partially reverts
7e7ab06ccda2befbd517a1b974da44fd6643f72e by disabling parallel builds,
as there are sporadic build failures again
Maintainer: me
Run tested: no, minor version bump only includes a single commit
Description:
Minor version bump and go back to disable parallel builds.

rtpengine: bump to 8.5.1.2, disable parallel build

---

net/rtpengine/Makefile

Maintainer: me
Run tested: gave it a quick runtest on 19.07 ath79
Description:
Version bump within the same LTS branch.

rtpengine: bump to 8.5.2.1 LTS

---

net/kamailio-5.x/Makefile
net/kamailio-5.x/patches/160-openssl-deprecated.patch

kamailio-5.x: fix compilation without deprecated OpenSSL APIs

---

net/rtpengine/Makefile
net/rtpengine/patches/05-support-kernels-greater-equal-5.9.9.patch

Patch from upstream fixes builds on recent kernels.
Closes #590
Maintainer: @jslachta & me
Description:

rtpengine: bump to 8.5.2.3 + add build fix

---

net/asterisk-16.x/Makefile
net/asterisk-16.x/patches/190-AST-2020-001-16.diff
net/asterisk-16.x/patches/200-AST-2020-002-16.diff

Patches used:
http://downloads.asterisk.org/pub/security/AST-2020-001-16.diff
http://downloads.asterisk.org/pub/security/AST-2020-002-16.diff
Patch AST-2020-002-16.diff was amended a bit in res/res_pjsip_session.c:
if (++session->authentication_challenge_count > MAX_RX_CHALLENGES) {
ast_debug(3, "%s: Initial INVITE reached maximum number of auth attempts.\n", ast_sip_session_get_name(session));
return PJ_FALSE;
}
The above was not possible, because of missing bits introduced only in a
later version of Asterisk 16 (see upstream commit [1]). So the ast_debug
call was simplified accordingly.
Both patches were refreshed within OpenWrt SDK.
[1] https://github.com/asterisk/asterisk/commit/6abf6f345dbd0510d8a217d16cc1819e4d2bf815 …

[19.07] asterisk-16.x: fix AST-2020-001 and 002

---

net/asterisk-13.x/Makefile
net/asterisk-13.x/patches/170-AST-2020-001-13.diff
net/asterisk-13.x/patches/180-AST-2020-002-13.diff

Patches used:
http://downloads.asterisk.org/pub/security/AST-2020-001-13.diff
http://downloads.asterisk.org/pub/security/AST-2020-002-13.diff
Patch AST-2020-002-16.diff was amended a small bit in
include/asterisk/res_pjsip_session.h due to Asterisk 13 getting some
updates in the meantime which are not in OpenWrt.
Both patches refreshed in OpenWrt SDK.
Compile tested: 18.06 ar71xx
Run tested: Nope, don't have 18.06 around.
Description:
Add upstream patches to fix vulns.

[18.06] asterisk-13.x: fix AST-2020-001 and 002

---

net/kamailio-5.x/Makefile
net/kamailio-5.x/patches/150-erlang-fix-flags.patch

Compile tested: archs38 + rtl838x
Run tested: don't have the hardware, but these are build-fixes only anyway.
Description:
Hi Jiri,
I was going around https://downloads.openwrt.org/snapshots/faillogs/ looking for builds that fail. I found Kamailio failing on uClibc targets due to Erlang (I expect the same for glibc). Kamailio also fails to build for the new rtl838x target. Fixes for both issues are included here.
I found one more build failure: asterisk-chan-sccp on uClibc targets. This is because OpenWrt doesn't build uClibc with XLOCALE support, I think. I can live with that :)
Kind regards,
Seb

kamailio-5.x: build fixes

---

libs/dahdi-linux/Makefile
libs/dahdi-tools/Makefile

Maintainer: @VittGam 
Run tested: on 19.07 ath70, ran some tools. I have no "dahdi" hw so I don't really know what I'm doing, but the programs seem to execute.
```
root@hank2:/tmp# dahdi_test 
Opened pseudo dahdi interface, measuring accuracy...
99.596% 99.590% 98.456% 99.591% 99.592% 99.592% 99.592% 98.451% 
99.592% 99.591% 99.592% 99.592% 98.458% 99.591% 99.593% ^C
--- Results after 15 passes ---
Best: 99.596% -- Worst: 98.451% -- Average: 99.364558%
Cumulative Accuracy (not per pass): 99.983
root@hank2:/tmp# dahdi_speed 
^C
root@hank2:/tmp# dahdi_speed -h
^C
root@hank2:/tmp# dahdi_speed -v
^C
root@hank2:/tmp# dahdi_
dahdi_cfg      dahdi_monitor  dahdi_scan     dahdi_speed    dahdi_test
root@hank2:/tmp# dahdi_
dahdi_cfg      dahdi_monitor  dahdi_scan …
```

dahdi: bump and cleanups

---

net/asterisk/Makefile

This addresses CVE-2020-35652 as described in:
https://downloads.asterisk.org/pub/security/AST-2020-003.html
https://downloads.asterisk.org/pub/security/AST-2020-004.html
Compile tested: No, I just confirmed that our patches apply fine (they do). CI will confirm the build.
Run tested: No, this is a micro version update that only includes one added patch (which is tiny).
Description:
Hi Jiri,
They announced AST-2020-003 and AST-2020-004 today, for which they received CVE-2020-35652. This is related to History-Info header support, which they added in 2019 (correction: in September 2020, actually). I checked in 19.07 and there we do not have History-Info header support yet, so we …

asterisk: micro version bump to 18.1.1

---

net/freeswitch/Makefile
net/freeswitch/patches/040-gentls_cert_update_message_digest.patch
net/freeswitch/patches/230-mod_radius_cdr.patch
net/freeswitch/patches/410-mod_rayo_enable-f-no-common-compilation.patch

Fix patch 230 as it's a patch of a patch with fuzz and wrong offsets.
Refresh other patches.
Compile tested: powerpc

freeswitch: fix compilation with musl 1.2.0

---

net/asterisk/Makefile
net/asterisk/patches/150-lua-ldl.patch

Currently building for archs target against glibc fails:
checking for mandatory modules:  CAP GSM ILBC LIBEDIT LIBXML2 LUA PJPROJECT SQLITE3 SRTP ZLIB... fail
configure: ***
configure: *** The LUA installation appears to be missing or broken.
Checking config.log reveals:
/home/sk/tmp/sdk/openwrt-sdk-archs38-generic_gcc-8.4.0_glibc.Linux-x86_64/staging_dir/toolchain-arc_archs_gcc-8.4.0_glibc/bin/../lib/gcc/arc-openwrt-linux-gnu/8.4.0/../../../../arc-openwrt-linux-gnu/bin/ld: /home/sk/tmp/sdk/openwrt-sdk-archs38-generic_gcc-8.4.0_glibc.Linux-x86_64/staging_dir/target-arc_archs_glibc/usr/lib/liblua.so: undefined reference to `dlopen'
/home/sk/tmp/sdk/openwrt-sdk-archs38-generic_gcc-8.4.0_glibc.Linux-x86_64/staging_dir/toolchain-arc_archs_gcc-8.4.0_glibc/bin/../lib/gcc/arc-openwrt-linux-gnu/8. …

asterisk: link in libdl when linking to liblua

---

net/siproxd/Makefile
net/siproxd/files/siproxd.init

**Maintainer**: @jslachta
**Compile tested**: qemu/malta-mips32-be, master branch
**Run tested**: qemu/malta-mips32-be, master branch
**IB tested**: ar71xx/mips32-be, 19.07.6 (confirmed absence of  'readonly variable' warning)
**Description**:
Variable 'UID' is set readonly in some calling contexts, yielding errors during e.g. ImageBuilder usage:
```
...
Enabling rpcd
./etc/init.d/siproxd: line 14: UID: readonly variable
Enabling siproxd
Enabling sysctl
...
```
Rename UID and GID variables as SIPROXD_UID and SIPROXD_GID.
Signed-off-by: Tony Ambardar <itugrok@yahoo.com>

siproxd: fix UID variable conflict in init

---

net/rtpengine/Makefile
net/rtpengine/patches/02-pcap.patch

In other news:
- removes "mr" from version
- refreshes patches/02-pcap.patch
Maintainer: me
Run tested: 
Description:
Bump. It remains in the same LTS strain.

rtpengine: bump to 8.5.3.1

---

net/asterisk/Makefile

Uriparser is a compliant URI parsing and handling library for RFC 3986.
For now, this is not included in OpenWrt feeds, but in Turris OS
uriparser is used as dependency for Updater-ng.
When Asterisk finds in build system there is uriparser or anything else mentioned in configure,
it tries to enable it by default. This applies to every package in
OpenWrt and because of that new packages which are added to OpenWrt tries to disable almost
everything by default. Because if someone adds library, some packages
are not compiled or tested.
Fixes:
Package asterisk is missing dependencies for the following libraries:
liburiparser.so.1
Compile tested: Turris Omnia, Turris OS 6.0 (unreleased) based on the latest OpenWrt master (feeds, which were used …

asterisk: disable uriparser

---

net/asterisk/Makefile
net/asterisk/patches/001-disable-semaphores-on-uclibc-otherwise-allow.patch
net/asterisk/patches/002-configure-fix-detection-of-re-entrant-resolver-funct.patch
net/asterisk/patches/130-eventfd.patch
net/asterisk/patches/140-use-default-lua.patch
net/asterisk/patches/150-musl-12x.patch

Needs _DECLS and __P definitions.
Refreshed other patches.
Compile tested: powerpc

asterisk: fix compilation with 1.2.x

---

libs/dahdi-linux/Makefile

This sets PKG_EXTMOD_SUBDIRS so kernel.mk can find the DAHDI
Module.symvers file.
Also, this puts KERNEL_MAKE_FLAGS into the make flags. This way
Module.symvers files of other modules are made available, plus there is
no need anymore to specify ARCH and CROSS_COMPILE, as KERNEL_MAKE_FLAGS
already takes care of that.
TARGET_CONFIGURE_OPTS is dropped because this seems out of place
(configure vs. compile).
Maintainer:
Run tested:
Description: fix Module.symvers handling

dahdi-linux: fix Module.symvers handling

---

libs/pjproject/Makefile
libs/pjproject/patches/240-fix-sdp-neg-modify-local-offer.patch
net/asterisk-16.x/Makefile
net/asterisk-16.x/patches/180-AST-2019-007-16.diff
net/asterisk-16.x/patches/210-AST-2021-001-16.diff

Compile tested: 19.07 sdk ath79
Run tested: 19.07.6, made some test calls, also sent some DTMFs
Description:
Hi Jiri,
I went through the following notices:
https://downloads.asterisk.org/pub/security/AST-2021-001.html
https://downloads.asterisk.org/pub/security/AST-2021-002.html
https://downloads.asterisk.org/pub/security/AST-2021-003.html
https://downloads.asterisk.org/pub/security/AST-2021-004.html
https://downloads.asterisk.org/pub/security/AST-2021-005.html
https://downloads.asterisk.org/pub/security/AST-2021-006.html
I also looked at the Debian tracker:
https://security-tracker.debian.org/tracker/source-package/asterisk
It seems to me that in the 19.07 branch we only need to take care of two of them, AST-2021-001 and AST-2021-005. The other bugs were added …

[19.07] asterisk/pjproject: add patches for recently published Asterisk security notices

---

libs/pjproject/Makefile
libs/pjproject/patches/0070-fix-sdp-neg-modify-local-offer.patch

Run tested: Not really, I only run-tested the AST-2021-005 on 19.07.
Description:
Hi Jiri,
The other AST-2021-* notices are covered in asterisk 18.2.2, so once that's upgraded we're done for master. Would be great if these then could be cherry-picked to openwrt-21.02.
Kind regards,
Seb

pjproject: add fix for AST-2021-005 + brush up our Makefile

---

net/sngrep/Makefile

Maintainer: me
Compile tested: ath79 master + 19.07
Run tested: 19.07
Description: version bump

sngrep: bump to 1.4.8

---

net/freeswitch/Makefile
net/freeswitch/patches/003-modmake-fix.patch

Somehow this white space change slipped in unintentionally.
Maintainer: me
Description: Remove an unintended change in the modmake patch.

[21.02] freeswitch: fix 003-modmake-fix.patch

---

net/freeswitch-stable/Makefile
net/freeswitch-stable/patches/003-modmake-fix.patch

Somehow this white space change slipped in unintentionally.
Maintainer: me
Description: Remove unintended change in modmake patch.

[19.07] freeswitch-stable: fix 003-modmake-fix.patch

---

net/pcapsipdump/Makefile

Upstream implemented or updated IPv6 support.
This commit also updates the package title and fixes some
spelling/grammar in the package's description.
Compile tested: master for powerpc_464fp, 19.07 for ath79
Run tested: 19.07 ath79
```
root@hank2:/tmp/pcap# pcapsipdump -f -i br-lan  -n 6001 -d /tmp/pcap 
Capturing on interface: br-lan
^CSIGINT received, terminating
root@hank2:/tmp/pcap#
root@hank2:/tmp/pcap/20210501/11# ls -lht
-rw-r--r--    1 root     root      151.9K May  1 11:18 20210501-111829-6001-6002-616a4f20-54ef-4542-b897-a191337919e1.pcap
-rw-r--r--    1 root     root      153.5K May  1 11:18 20210501-111829-6001-6002-wI3qqvPGlX.pcap
root@hank2:/tmp/pcap/20210501/11# …
```

pcapsipdump: update to svn revision r157

---

net/kamailio/Makefile

Added new module lrkproxy. Module "userblacklist" was renamed upstream
to "userblocklist".
Compile tested: master ath79 + 19.07 ath79
Run tested: On 19.07 ath79 with rtpproxy and asterisk
```
Sat May  8 16:56:42 2021 daemon.err kamailio[13806]:  1(13813) WARNING: {20 REGISTER} sanity [sanity.c:612]: check_cl(): content length header missing in request
Sat May  8 16:56:42 2021 daemon.err kamailio[13806]:  1(13813) WARNING: {21 REGISTER} sanity [sanity.c:612]: check_cl(): content length header missing in request
Sat May  8 16:56:52 2021 daemon.err kamailio[13806]:  1(13813) NOTICE: {20 INVITE} Outbound call to local number 6001
Sat May  8 16:56:52 2021 daemon.err kamailio[13806]: …
```

kamailio: update to version 5.5.0

---

net/asterisk/Makefile
net/asterisk/patches/100-build-reproducibly.patch
net/asterisk/patches/130-eventfd.patch
net/asterisk/patches/140-use-default-lua.patch

Patches updated/refreshed:
100-build-reproducibly.patch
130-eventfd.patch
140-use-default-lua.patch
Signed-off-by: Jiri Slachta <jiri@slachta.eu>
Compile tested: x86
Run tested: x86
Description:

asterisk: update to 18.4.0

---

libs/sofia-sip/Makefile
libs/sofia-sip/patches/02-NUA_handles-mem-leak-fix.patch

Upstream provided a patch for a memory leak in Sofia SIP (see [1] for
more information).
[1] https://github.com/signalwire/freeswitch/issues/1174
Maintainer: me
Compile tested: master + 19.07 ath79
Run tested: 19.07 ath79, made a few test calls
Description: Mem leak fix from upstream

sofia-sip: add upstream fix for memory leak

---

libs/sofia-sip/Makefile
libs/sofia-sip/patches/02-NUA_handles-mem-leak-fix.patch

Upstream provided a patch for a memory leak in Sofia SIP (see [1] for
more information).
[1] https://github.com/signalwire/freeswitch/issues/1174
Maintainer: me
Compile tested: master + 19.07 ath79
Run tested: 19.07 ath79, made a few test calls
Description: Mem leak fix from upstream

[21.02] sofia-sip: add upstream fix for memory leak

---

libs/sofia-sip/Makefile
libs/sofia-sip/patches/02-NUA_handles-mem-leak-fix.patch

Upstream provided a patch for a memory leak in Sofia SIP (see [1] for
more information).
[1] https://github.com/signalwire/freeswitch/issues/1174
Maintainer: me
Compile tested: master + 19.07 ath79
Run tested: 19.07 ath79, made a few test calls
Description: Mem leak fix from upstream

[19.07] sofia-sip: add upstream fix for memory leak

---

net/yate/Makefile
net/yate/patches/120-increase-sip-message-size.patch

Some SIP UAs support lots of features and codecs which results in
large SIP messages. YATE, with its default configuration, truncates
and fails to parse received SIP messages which are larger than 1500
bytes. Let's increase the default max message size for OpenWrt users
to make it easier to use yate out-of-the-box.
The new max size of 8192 bytes has been arbitrarily chosen.
I've seen the SIP UA baresip produce messages larger than 1500 bytes
with its default configuration when authentication is used.
Signed-off-by: Robert Högberg <robert.hogberg@gmail.com>
Compile tested: No
Run tested: Only by manual configuration change. An increased maxpkt size works well for me. Verified with SIP UA baresip that had problems with YATE before the …

yate: increase max acceptable size of incoming SIP messages

---

libs/dahdi-tools/Makefile
libs/dahdi-tools/patches/030-cdefs.patch

dahdi-tools: fix compilation with musl 1.2.x

---

net/asterisk/Makefile
net/asterisk/patches/090-app_dial-expanded-A-option-to-add-caller-announcement.patch

Compile tested: x86/64, OpenWrt master
Run tested: x86/64, OpenWrt master and OpenWrt 21.02-SNAPSHOT
Description:
Update to upstream version 18.5.0 and backport commit[1] completing the
announcements in Dial command to behave like it is stated in the
documenation[2].
[1]: https://github.com/asterisk/asterisk/commit/1e5a2cfe3037823b17dd4ac47b071f02d6f9825f
[2]: https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+Application_Dial

asterisk: update to version 18.5.0 and backport patch

---

net/kamailio/Makefile
net/kamailio/patches/070-dont-override-arm-march.patch

src/Makefile.defs adds "-march=..." to target flags for ARM targets.
This can clash with the OpenWrt target flags in
CONFIG_TARGET_OPTIMIZATION. If for example the latter is set to
"-mcpu=cortex-a9" the following warning is issued:
cc1: warning: switch '-mcpu=cortex-a9' conflicts with '-march=armv5t' switch
This commit removes these flags. The addition is unwanted when
cross-compiling.
An issue was raised for this recently, see [1].
[1] https://github.com/openwrt/packages/issues/16135
Compile tested: CI
Run tested: No
Description:
Hello @ByteEnable
Please try this and provide feedback. Thanks.
Regards,
Seb

kamailio: prevent arm -march overrides

---

libs/gsmlib/Makefile

throw() was removed in C++17, which GCC11 defaults to.

gsmlib: set C++ standard to 11

---

net/freeswitch/Makefile
net/freeswitch/patches/040-gcc11.patch
net/freeswitch/patches/050-c++.patch

GCC 11 is more strict with declarations.

freeswitch: fix compilation with GCC11

---

net/freeswitch/Makefile
net/freeswitch/files/freeswitch.init

This sets STOP to 10 to allow for a
graceful shutdown. Users may additionally need to set "term_timeout" in
/etc/config/freeswitch to a sensible value.
Maintainer: me
Run tested: 21.02 ath79
Description:
Update init script a bit after seeing some commits from stintel in "packages" repo. Makes sense to give FS a chance to clean up during shutdown.

freeswitch: set stop level

---

libs/gsmlib/Makefile
libs/gsmlib/patches/01-update-autotools.patch

It's not wanted, so add "--disable-nls" to override user selecting
CONFIG_BUILD_NLS.
configure.in and Makefile.am are slightly changed to make these
disappear:
ERROR: Use of AM_GNU_GETTEXT without [external] argument is no longer supported.
Makefile.am:21: warning: 'intl' should not be in SUBDIRS when AM_GNU_GETTEXT([external]) is used
Maintainer: me
Run tested: -
Description:

gsmlib: disable NLS

---

net/freeswitch/patches/230-mod_radius_cdr.patch

POSIX shells don't support "+=" operators. This commit replaces it with
something portable.
Maintainer: me
Run tested: no, build fix
Description:
Hi @neheb,
This fixes it, right? Any more of these issues or is this it?
Kind regards,
Seb

freeswitch: remove "+=" operator for portability

---

net/rtpengine/Makefile

This also:
- fixes /etc/modules.d/ipt-rtpengine (needs user and group ids instead
of names)
- adds user as well when kmod is installed so that abovementioned user
and group ids are available
- adds /etc/modules.d/ipt-rtpengine to conffiles
Maintainer: me
Compile tested: 21.02 SDK
Run tested: at79 21.02 rc4 with kamailio on router, asterisk on laptop and some phones
Description:
Bump + module options load fix

[21.02] rtpengine: bump to version 8.5.5.1

---

net/asterisk/patches/160-AST_EXT_TOOL_CHECK.patch

Issue #672 shows that the current macro has some pitfalls, at least when
running within OpenWrt's buildroot.
The macro is used to detect these tools:
1. xml2-config
2. mysql_config
3. neon-config
4. net-snmp-config
5. sdl-config (we're not using SDL)
The macro also adds configure arguments that allow to specify a path
like so:
--with-mysqlclient=PATH
Macro problems:
1. If no PATH is specified, it adds "/bin" to the search path.
Obviously this is a bad thing when cross-compiling.
2. If a PATH is specified, it adds it to the start of every include
and library path it encounters. These paths are then broken.
This commit makes problem 1 go away by making the addition of
"${$1_DIR}/bin" to the PATH dependent on there being a PATH handed to
the macro. An alternative would be to remove the PATH …

asterisk: update AST_EXT_TOOL_CHECK for OpenWrt

---

net/yate/Makefile

Sporadic build failures are visible on the build bots.
```
libyate.so: undefined reference to `TelEngine::ClientLogic::initStaticData()'
libyate.so: undefined reference to `TelEngine::DefaultLogic::DefaultLogic(char const*, int)'
collect2: error: ld returned 1 exit status
```
Turning off parallel builds should (hopefully) work around this.
Description:
This should hopefully take care of issue #688

yate: disable parallel builds

---

net/freeswitch/Makefile
net/freeswitch/files/freeswitch.init

Currently the freeswitch init script starts the service with the group
"freeswitch". Like this, even if the freeswitch user is part of other
groups, freeswitch will not be able to make use of them. So for instance
if you add the user to the group "dialout", freeswitch will run under
group "freeswitch", instead of "freeswitch" _and_ "dialout".
Not specifying the group gets rid of this limitation.
Maintainer: me
Compile tested: N/A (init script change)
Run tested: 21.02 on ath79
Description:
Fixup the issue where the freeswitch user is added to different groups and the freeswitch software isn't able to make use of it.

freeswitch: don't start with explicit group

---

net/asterisk-opus/Makefile
net/asterisk-opus/patches/01-Makefile.patch

I've been using this for ~5 months now, works for me (tm).
In my case I store voicemail recording as .opus files and send those out via email.
There's currently no support to set the encoder properties using codecs.conf as I don't have a use case for it.
Noteworthy is that the encoding complexity is set to 4 (from the default of the max 10) on soft float devices, as they can't keep up encoding in realtime.
4 works for me on lantiq/xrx200, so a rather old and slow device.

asterisk: add opus read and write support

---

net/sngrep/Makefile

- switch to $(AUTORELEASE)
- drop PKG_MIRROR_HASH (leftover from when a git checkout was used)
Maintainer: me
Compile tested: sdk master from yesterday
Run tested: sdk master from yesterday, ath79
Description:
Version bump. Checked with asterisk and some sip phones. sngrep worked fine, now has a nice RTP counter "animation".

sngrep: bump to 1.4.10

---

libs/re/Makefile
libs/re/patches/001-extend-ninit-nclose-check.patch
libs/re/patches/004-prevent-optimization-meddling.patch
libs/re/patches/005-fix-builds-for-mipsel-targets.patch
libs/rem/Makefile
net/baresip/Makefile
net/baresip/patches/002-fix-rem-include.patch

Compile tested: 21.02
Run tested: 21.01
Description:
I don't use baresip myself, so a bit hard to run-test. But I got it to send me back a ringing with the b2bua module. It's not much, but that was as much time as I was willing to invest in this. It took me long enough getting the new version to build.
```
Mon Dec  6 23:31:22 2021 daemon.err baresip[9292]: unhandeled request from 192.168.0.151:46932: REGISTER sip:192.168.0.1
Mon Dec  6 23:33:56 2021 daemon.err baresip[9292]: unhandeled request from 192.168.0.151:46598: REGISTER sip:192.168.0.1
Mon Dec  6 23:34:03 2021 daemon.info baresip[9292]: ua: sipsess connect via UDP 192.168.0.151:46598 --> 192.168.0.1:5080
Mon Dec  6 23:34:03 2021 daemon.info baresip[9292]: b2bua-inbound@192.168.0.1: use catch-all account for …
```

baresip: bump to 1.1.0 (re to 2.0.1 and rem to 1.0.0)

---

net/restund/Makefile
net/restund/patches/200-turn-block-forwarding-to-loopback-any.patch
net/restund/patches/201-turn-also-don-t-forward-linklocal-addresses.patch
net/restund/patches/202-turn-block-whole-loopback-range-also-block-broadcast.patch

Patches taken from [1].
[1] https://github.com/wireapp/restund/pull/7
(cherry picked from commit dec6316f2f9204f3c34fadc7616435ddecf19e6c)
------------------------------
Compile tested: 21.02
Run tested: 21.02
Description:
Cherry-pick form 21.02 branch to 19.07

[19.07] restund: fix CVE-2021-21382

---

net/restund/Makefile
net/restund/patches/200-turn-block-forwarding-to-loopback-any.patch
net/restund/patches/201-turn-also-don-t-forward-linklocal-addresses.patch
net/restund/patches/202-turn-block-whole-loopback-range-also-block-broadcast.patch

Patches taken from [1].
[1] https://github.com/wireapp/restund/pull/7
Compile tested: 21.02
Run tested: 21.02
Description: Without the patches I was able to follow [this tutorial](https://gist.github.com/cameronelliott/be1e581cb7b28f748e04bcabc249e6b6) and test restund on localhost. With the patches applied the negotiation is still fine, but no Turn packets are sent for bindings to localhost by restund anymore. So the patches seem to work as far as I can tell.

[21.02] restund: fix CVE-2021-21382

---

net/restund/Makefile
net/restund/patches/200-turn-block-forwarding-to-loopback-any.patch
net/restund/patches/201-turn-also-don-t-forward-linklocal-addresses.patch
net/restund/patches/202-turn-block-whole-loopback-range-also-block-broadcast.patch

Patches taken from [1].
Added a postinstall note about the upcoming deletion of this package.
[1] https://github.com/wireapp/restund/pull/7
(cherry picked from commit dec6316f2f9204f3c34fadc7616435ddecf19e6c)
Compile tested: 21.02
Run tested: 21.02
Description:
Instead of directly deleting restund from master, patch it and add a postinstall for users. I'll set a reminder for February and we can delete the package then.

restund: fix CVE-2021-21382

---

net/baresip/Makefile

Compile tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master
Fixes issue:
```
ccache_cc -L//master/build/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr/lib -fPIC -L//master/build/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/usr/lib -L//master/build/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/lib -DPIC -fpic -specs=//master/build/include/hardened-ld-pie.specs -znow -zrelro -shared  \
build-arm/modules/opus/decode.o build-arm/modules/opus/encode.o build-arm/modules/opus/opus.o build-arm/modules/opus/sdp.o \
-lopus -lm -L//master/build/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr/lib -lre -o opus.so
//master/build/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/lib/gc …
```

baresip: fix compilation with NLS

---

net/coturn/Makefile

If turndb it created in this folder it should be saved during
sysupgrade.
Maintainer: me / @jslachta 
Compile tested: NA
Run tested: NA
Description:

coturn: add /etc/turnserver to conffiles

---

net/kamailio/Makefile
net/kamailio/patches/160-ldap-rename-private-function-ldap_connect.patch
net/kamailio/patches/170-core-add-support-for-time64-libcs.patch

Compile tested: master sdk
Run tested: master (I have to admit that I don't use any of the affected plugins)
Description:
Hi all,
This adds two patches. One fixes compile issue related to recent openldap update (currently kamailio doesn't build on the build bots). The other fixes time_t issues (compile warnings are currently visible on master when compiling against musl 1.2). All changes are upstreamed already.
Kind regards,
Seb

kamailio: add upstreamed patches (compile fix + time64 fixes)

---

net/coturn/Makefile
net/coturn/patches/100-configure-dont-link-libintl.patch

Maintainers: @jslachta and @micmac1 
Issue reproduced on these two routers:
- Turris MOX, mvebu, (cortex-a53), OpenWrt master
- Turris Omnia, mvebu (cortex-a9), OpenWrt master
and on the later one, I was able to reproduce this issue locally and fix it as well. I didn't had the build environment for the first one, yet. Thus proposing this fix.
If there is enabled CONFIG_BUILD_NLS, coturn can not be compiled.
It fails with the following error:
Package coturn is missing dependencies for the following libraries:
libintl.so.8

coturn: add libintl dependency when enabled full language support

---

net/rtpengine/Makefile

Latest LTS release. Switch to AUTORELEASE.
Maintainer: me
Compile tested: recent ath79 master SDK
Description: Version bump

rtpengine: bump to 9.5.3.2

---

libs/sofia-sip/Makefile

Contains DOS fix, see [1].
Converted to AUTORELEASE.
[1] https://github.com/signalwire/freeswitch/issues/1518
Maintainer: me
Run tested: 19.07 ath79
Description: version bump

sofia-sip: update to 1.13.7

---

libs/sofia-sip/Makefile

Contains DOS fix, see [1].
Converted to AUTORELEASE.
[1] https://github.com/signalwire/freeswitch/issues/1518
(cherry picked from commit f04a5a23830ced20e0bd298f41fb9fd93c8353a0)
Maintainer: me
Compile tested: sdk ath79 master
Run tested: 19.07 ath79
Description: version bump

[21.02] sofia-sip: update to 1.13.7

---

libs/libpri/Makefile
libs/libpri/patches/001-fix-include-signal-h-warning.patch
libs/libpri/patches/100_add-an-ability-to-build-libpri-on-MacOS-for-Linux-ta.patch

libpri can not be built on macos for OpenWrt Linux target due to:
1. Makefile uses `ar` and `ranlib` (without using make variables).
MacOS system ar and ranlib are not compatible with the objects
generated by OpenWrt GCC toolchain. This commit adds patch to
add an ability to redefine `ar` and `ranlib` tools.
Upstream issue: https://issues.asterisk.org/jira/browse/PRI-188
2. Makefile detects Darwin using `uname -s` and changes build logic
but it is not need for cross-platfrom build. This commit
redefines OSARCH=Linux in OpenWrt Makefile
3. After redefining OSARCH=Linux, libpri Makefile uses /sbin/ldconfig
that does not exist on MacOS. This commit redefines LDCONFIG=ldconfig
in OpenWrt Makefile to use ldconfig provided by OpenWrt.
Patch '001-fix-include-signal-h-warning.patch' was refreshed …

libpri: fix build on macos

---

net/coturn/Makefile

This PR has two commits:
coturn: improve reproducibility (Ubuntu build host fix)
coturn: fix build on macos
Maintainer: @jslachta , Sebastian Kemper <sebastian_ml@gmx.net>
Compile tested: (armvirt/64, OpenWRT version b21bc3479d46e6a4c3cc6bf7c245d4b0ddccb7db)
Run tested: not really tested, but generated binaries are exactly the same as official binaries from https://downloads.openwrt.org/snapshots/packages/ . Now generated binaries are the same on Debian, Ubuntu and MacOS build hosts
CI status for first commit (reproducibility) is: https://github.com/svlobanov/telephony/runs/5024603191
CI status for both commits will be in this PR and by link: https://github.com/svlobanov/telephony/runs/5024839078

coturn: improve reproducibility and fix build on macos

---

net/yate/Makefile

yate configure script uses `uname -s` to determine OS and changes
build logic regarding to build host OS. OpenWrt is always Linux so
it should be built as for Linux.
This patch uses fakeuname tool to pass `uname -s` checks as Linux
on macos build host.
Signed-off-by: Sergey V. Lobanov <sergey@lobanov.in>
Compile tested: (armvirt/64, OpenWRT version b21bc3479d46e6a4c3cc6bf7c245d4b0ddccb7db)
Description: see above

yate: fix build on macos

---

net/kamailio/Makefile

kamailio macos build fails due to kamailio Makefile checks OS
(`uname -s`) and OSREL (`uname -r`). If build host is not Linux,
then these checks will provide different results, but OpenWrt is
always Linux so target OS should be always Linux.
This patch explicitly specifies OS=linux and OSREL=$(LINUX_UNAME_VERSION)
to avoid using build host values for target build.
Signed-off-by: Sergey V. Lobanov <sergey@lobanov.in>
Compile tested: (armvirt/64, OpenWRT 4d904524effc9eb0cc5094574c55d3a520803223)
Description: see above

kamailio: fix build on macos

---

libs/libosip2/Makefile
net/siproxd/Makefile

Maintainer: @jslachta @guidosarducci 
Compile tested: master ath79 SDK
Description:
This bumps libosip2 to latest release and siproxd to latest upstream git commit. siproxd update contains fixes related to time64 and also allows for a reproducible build.
Closes #613
Closes #742

siproxd/libosip2: update to latest

---

libs/pjproject/patches/0111-ssl-premature-destroy.patch

AST-2021-009 has two patches, the second of which was missed.
Compile tested: ath79 master SDK
Description: add missing patch

pjproject: add missing patch for AST-2021-009

---

libs/pjproject/Makefile
libs/pjproject/patches/0111-ssl-premature-destroy.patch

AST-2021-009 has two patches, the second of which was missed.
(cherry picked from commit 1ac119d6c897950f8f1719b4c7c26c63cb060d2e)
Compile tested: ath79 master SDK
Description: add missing patch

[21.02] pjproject: add missing patch for AST-2021-009

---

net/rtpengine/Makefile

utils/const_str_hash is called by rtpengine build system. The Perl
script uses shebang "#!/usr/bin/perl" and depends on perl-IPC-Cmd. If
this is missing the build will fail:
../utils/const_str_hash < "control_ng.c" > "control_ng.strhash.c"
Can't locate IPC/Cmd.pm in @INC (you may need to install the IPC::Cmd module) (@INC contains: /usr/local/lib64/perl5/5.34 /usr/local/share/perl5/5.34 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ../utils/const_str_hash line 6.
BEGIN failed--compilation aborted at ../utils/const_str_hash line 6.
make[4]: *** [../lib/common.Makefile:46: control_ng.strhash.c] Error 2
OpenWrt does not depend on perl-IPC-Cmd being available, so this commit
makes rtpengine build depend on perl/host, which provides this Perl …

rtpengine: use perl/host when building

---

net/freeswitch/Makefile

FS is not yet ready for FFMPEG 5.0. Upstream has a related issue already
([1]).
Also move to AUTORELEASE.
[1] https://github.com/signalwire/freeswitch/issues/1560
Maintainer: me
Description:

freeswitch: mark mod-av BROKEN

---

libs/pjproject/Makefile
libs/pjproject/patches/0170-stun-integer-underflow.patch
libs/pjproject/patches/0171-dialog-set-free.patch
libs/pjproject/patches/0172-prevent-multipart-oob.patch

Details:
https://downloads.asterisk.org/pub/security/AST-2022-004.html
https://downloads.asterisk.org/pub/security/AST-2022-005.html
https://downloads.asterisk.org/pub/security/AST-2022-006.html
(cherry picked from commit 623e5288f16baa64472eefbbd215aacb0f99e79f)
Compile tested: 21.02.2 SDK
Run tested: 21.02.2 ath79
Description:
Cherry-pick from master, incremented PKG_RELEASE.

[21.02] pjproject: add upstream security fixes

---

net/asterisk/files/asterisk.conf
net/asterisk/files/asterisk.init

Compile tested: x86_64, generic, HEAD (236c3ea730)
Run tested: same, installed & running on production PBX
Description:
Don't duplicate console tracing into `/var/log/messages`.

asterisk: don't send stdout to syslog by default

---

net/asterisk/Makefile

Since upstream commit b40c4d59b1dd803cad79060fb5b5a48d249ba578
"--disable-xmldoc" does no longer prevent the linking to libxslt, if
available. If that's the case one is greeted with the following error:
Package asterisk is missing dependencies for the following libraries:
libxslt.so.1
This commit explicitly disables the use of libxslt, to avoid the
dependency.
Description: prevent use of libxslt if available in staging

asterisk: add --without-libxslt to configure

---

net/asterisk/Makefile

Since upstream commit b40c4d59b1dd803cad79060fb5b5a48d249ba578
"--disable-xmldoc" does no longer prevent the linking to libxslt, if
available. If that's the case one is greeted with the following error:
Package asterisk is missing dependencies for the following libraries:
libxslt.so.1
This commit explicitly disables the use of libxslt, to avoid the
dependency.
(cherry picked from commit 64a1d2faef62352327c4aaeec803ce71ff5d2c40)
Description: prevent use of libxslt if available in staging

[22.03] asterisk: add --without-libxslt to configure

---

libs/libsrtp/Makefile

Use OpenSSL instead of the internal crypto backend. Everything in
OpenWrt that links to libsrtp2 depends on OpenSSL anyway.
Upsides:
- the libsrtp2 package size shrinks a bit (for example from 35 to 24
KiB on ath79)
- allows to use more cipher suites
- may allow for hardware acceleration
Closes #763
Compile tested: 22.03-rc1 ath79
Run tested: 22.03-rc1 ath79, made some calls using SRTP (sdes)
Description:
Hi all,
PR to fix the recently opened issue.
Kind regards,
Seb

libsrtp: use OpenSSL

---

libs/sofia-sip/Makefile

Some security issues were fixed. Upstream labelled them as follows:
GHSA-79jq-hh82-cv9g: Fix Out-of-bound read in sip_method_d
GHSA-g3x6-p824-x6hm: Fix Out-of-bound read in url_canonize2 and
url_canonize3
GHSA-8w5j-6g2j-pxcp: Fix Heap-buffer-overflow in parse_descs and
parse_message
Maintainer: me
Run tested: Tested from freeswitch, made some test call.
Description: Minor version bump with security fixes. Will merge this into master tonight. I'll cherry-pick this to all supported branches tomorrow.
Kind regards,
Seb

sofia-sip: bump to 1.13.8

---

libs/sofia-sip/Makefile

Some security issues were fixed. Upstream labelled them as follows:
GHSA-79jq-hh82-cv9g: Fix Out-of-bound read in sip_method_d
GHSA-g3x6-p824-x6hm: Fix Out-of-bound read in url_canonize2 and
url_canonize3
GHSA-8w5j-6g2j-pxcp: Fix Heap-buffer-overflow in parse_descs and
parse_message
(cherry picked from commit 1efc4f3f98ed46b8bef2e29710d04131cda8ad44)
Maintainer: me
Compile tested: 
Run tested: 
Description:
Cherry-pick to address security issues in sofia-sip.

[openwrt-21.02] sofia-sip: bump to 1.13.8

---

libs/sofia-sip/Makefile

Some security issues were fixed. Upstream labelled them as follows:
GHSA-79jq-hh82-cv9g: Fix Out-of-bound read in sip_method_d
GHSA-g3x6-p824-x6hm: Fix Out-of-bound read in url_canonize2 and
url_canonize3
GHSA-8w5j-6g2j-pxcp: Fix Heap-buffer-overflow in parse_descs and
parse_message
(cherry picked from commit 1efc4f3f98ed46b8bef2e29710d04131cda8ad44)
Maintainer: me 
Compile tested: 
Run tested: 
Description:
Cherry-pick to address security issues in sofia-sip.

[openwrt-22.03] sofia-sip: bump to 1.13.8

---

net/sngrep/Makefile

- use pcre2 instead of pcre
- add zlib support
Maintainer: me
Description:
Version bump

sngrep: bump to 1.6.0

---

libs/sofia-sip/Makefile

Maintainer: me
Description: minor version bump

sofia-sip: bump to 1.13.9

---

net/rtpengine/Makefile
net/rtpengine/patches/05-use-spandsp3.patch

Maintainer: @jslachta / me 
Compile tested: master/22.03 ath79
Run tested: 22.03 ath79
```
Version: 10.5.2.6
Sat Oct 15 00:43:32 2022 user.err rtpengine: service not enabled
Sat Oct 15 00:43:32 2022 user.err rtpengine: edit /etc/config/rtpengine
Sat Oct 15 00:44:57 2022 user.notice rtpengine: instance instance1 has started
Sat Oct 15 00:44:58 2022 daemon.info rtpengine[14078]: INFO: [crypto] Generating new DTLS certificate
Sat Oct 15 00:44:58 2022 daemon.err rtpengine[14078]: ERR: [core] FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
Sat Oct 15 00:44:58 2022 daemon.err rtpengine[14078]: [1665787498.373282] ERR: [core] FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
Sat Oct 15 00:44:58 2022 daemon.info …
```

rtpengine: bump to 10.5.2.6

---

net/rtpengine/Makefile

rtpengine will use the lib if found, so add it.
Maintainer: @jslachta / me
Description: add missing dep
Sorry Jiri, didn't see that yesterday :) I'll just wait for CI to complete and merge it after. Have a good weekend!

rtpengine: add mqtt dep

---

net/asterisk/Makefile
net/asterisk/patches/130-eventfd.patch
net/asterisk/patches/140-use-default-lua.patch

No longer existing modules removed from OpenWrt Makefile. Same for configure switches. Patches refreshed.
Compile tested: ath79 master/22.03
Run tested: ath79 22.03, made some test calls
Description: version bump, luckily no pjproject changes compared to 18

asterisk: bump to 20.0.0 LTS

---

libs/gsmlib/Makefile
libs/gsmlib/patches/01-update-autotools.patch

It's not wanted, so add "--disable-nls" to override user selecting CONFIG_BUILD_NLS.
This also updates 01-update-autotools.patch to make these disappear:
ERROR: Use of AM_GNU_GETTEXT without [external] argument is no longer supported.
Makefile.am:21: warning: 'intl' should not be in SUBDIRS when AM_GNU_GETTEXT([external]) is used
(cherry picked from commit b86cf0cdc66d056be13ae49563d9bf5aadf28e78)
Maintainer: me
Compile tested: 21.02 SDK ath79
Description: backport to 21.02 as requested by Josef in #674

[21.02] gsmlib: disable NLS

---

net/freeswitch/patches/500-libshout-deprecated.patch

The recent libshout update causes compile failures due to deprecation. This works around it. Can be removed once issue is fixed upstream.
Maintainer: me
Compile tested: ath70 master
Description: lets make mod-shout compile again

freeswitch: workaround mod-shout compile failure

---

net/asterisk/files/asterisk.init
net/baresip/files/baresip.init
net/coturn/Makefile
net/coturn/files/turnserver.init
net/freeswitch/files/freeswitch.init
net/kamailio/files/kamailio.init
net/rtpproxy/files/rtpproxy.init

Maintainer: @jslachta & me
Run tested: 22.03 ath79
Description: Hi all,
I saw the commit [1] in packages. It fixed a bunch of init scripts to use return instead of exit in shell functions. I think we should do the same.
Usually we use "exit 1" in "start_service()" in our procd init scripts. Changing this to return is the right thing to do. There is a difference, though. If we run into "exit 1" we exit everything and the return value of the init script is "1". When converted to "return 1" the init script returns "0". So you could be in for a surprise if anything checked that return value. But in the files we provide we don't do that (e.g. freeswitch hotplug script calls init script but doesn't check return value).
Also, in rtpproxy and kamailio we use "exit 1" …

Treewide: Use return in init scripts instead of exit

---

libs/sofia-sip/Makefile

Maintainer: me
Compile tested: SDK 22.03 ath79
Run tested: ath79 22.03, made some phone calls with freeswitch
Description:
Minor version bump

sofia-sip: bump to 1.13.11

---

net/rtpengine/Makefile

The rtpengine daemon requires lws_get_ssl(). This function is not available in libwebsockets-mbedtls. This commit updates the dependency to libwebsockets-openssl.
Maintainer: me & @jslachta 
Compile tested: sdk ath79
Run tested: 22.03 with libwebsockets-full, but that should be the same as libwebsockets-openssl as far as lws_get_ssl() is concerned.
Description:
Update dependency as per #796

rtpengine: update libwebsockets dependency

---

net/rtpengine/Makefile

The rtpengine daemon requires lws_get_ssl(). This function is not available in libwebsockets-mbedtls. This commit updates the dependency to libwebsockets-openssl.
Maintainer: me & @jslachta 
Compile tested: 22.03 ath79 sdk
Run tested: 22.03 with libwebsockets-full, but that should be the same as libwebsockets-openssl as far as lws_get_ssl() is concerned.
Description:
Update dependency as per #796

[22.03] rtpengine: update libwebsockets dependency

---

net/baresip/Makefile
net/baresip/patches/010-fix-parallel-build.patch

Compile tested: arm, aarch64
Run tested: none
Description:
Include an upstream patch to fix random parallel build failures, such as:
```
CC [M]  build-arm/modules/ctrl_dbus/ctrl_dbus.o
modules/ctrl_dbus/ctrl_dbus.c:69:10: fatal error: baresipbus.h: No such file or directory
69 | #include "baresipbus.h"
|          ^~~~~~~~~~~~~~
```
Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

baresip: fix parallel build

---

net/freeswitch/Makefile

Cherry pick commit 09ad78b6cce247f4e610be006d89dfe70003aa58 which should resolve build issue.
```
CC       src/libfreeswitch_la-switch_hashtable.lo
src/switch_curl.c: In function 'switch_curl_process_form_post_params':
src/switch_curl.c:90:41: error: 'curl_formadd' is deprecated: since 7.56.0. Use curl_mime_init() [-Werror=deprecated-declarations]
90 |                                         curl_formadd(&formpost,
|                                         ^~~~~~~~~~~~
```
I'm guessing this is related to recent curl update in 22.03 branch.
Maintainer: me
Description: backport build fix

[22.03] freeswitch: backport commit "allow building with OpenSSL 3.0"

---

net/freeswitch/Makefile

mod-python3 is not compatible with Python 3.11 currently, mark it BROKEN.
Maintainer: me
Compile tested: ath70 sdk
Description:

freeswitch: mark mod-python3 BROKEN

---

net/kamailio/Makefile
net/kamailio/patches/170-app_python3-use-new-Python-3.10-API-functions-for-tr.patch
net/kamailio/patches/171-app_python3-proper-check-of-PY_VERSION_HEX-for-pytho.patch
net/kamailio/patches/172-app_python3-use-Py_SET_TYPE-from-python-3.9.patch

Python was updated to 3.11 and app_python3 doesn't compile anymore. This commit adds three upstream patches to resolve this.
Maintainer: @jslachta (I'll merge this once CI is done)
Compile tested: ath79 sdk
Description:

kamailio: add patches for app_python3

---

net/freeswitch/Makefile

mod-python3 is not compatible with Python 3.11 currently, mark it BROKEN.
(cherry picked from commit 2d4c2d2361314fe622c114a03dc8caa0b802505f)
Maintainer: me 
Compile tested: N/A, cherry-pick from master
Description: cherry-pick yesterday's commit to 23.05 because there Python 3.11 was also added.

[23.05] freeswitch: mark mod-python3 BROKEN

---

net/kamailio/Makefile
net/kamailio/patches/170-app_python3-use-new-Python-3.10-API-functions-for-tr.patch
net/kamailio/patches/171-app_python3-proper-check-of-PY_VERSION_HEX-for-pytho.patch
net/kamailio/patches/172-app_python3-use-Py_SET_TYPE-from-python-3.9.patch

Python was updated to 3.11 and app_python3 doesn't compile anymore. This commit adds three upstream patches to resolve this.
(cherry picked from commit 4483312785de91630765abaa3c8ef7d223f6dfee)
Maintainer: @jslachta (I'll merge once CI is done)
Compile tested: N/A, cherry-pick from master
Description: cherry-pick yesterday's commit to 23.05 because there Python 3.11 was also added.

[23.05] kamailio: add patches for app_python3

---

libs/pjproject/Makefile

1. add "/refs/tags" to PKG_SOURCE_URL, otherwise the downloaded file is broken now
2. bump minor version, includes security related fixes, see [1], [2] and [3]
[1] https://github.com/pjsip/pjproject/security/advisories/GHSA-9pfh-r8x4-w26w
[2] https://github.com/pjsip/pjproject/security/advisories/GHSA-cxwq-5g9x-x7fr
[3] https://github.com/pjsip/pjproject/security/advisories/GHSA-q9cp-8wcq-7pfr
Description:
upstream security fixes

pjproject: bump to 2.13.1

---

net/asterisk/Makefile
net/asterisk/patches/190-chan_iax2.c-Avoid-crash-with-IAX2-switch-support.patch

Reported by Sergio in issue #821. This adds upstream patch for the crash. See upstream issue [1] for details.
[1] https://github.com/asterisk/asterisk/issues/180
Compile tested: sdk ath79
Description:
See #821

asterisk: add upstream patch against iax2 crash

---

net/asterisk/Makefile
net/asterisk/patches/190-chan_iax2.c-Avoid-crash-with-IAX2-switch-support.patch

Reported by Sergio in issue #821. This adds upstream patch for the crash. See upstream issue [1] for details.
[1] https://github.com/asterisk/asterisk/issues/180
(cherry picked from commit 3d063acb25d745479df94d7731b90773d52b8e8a)
Description: cherry-pick from master, asterisk is the same in master and 23.05

[23.05] asterisk: add upstream patch against iax2 crash

---

net/asterisk/Makefile
net/asterisk/patches/180-chan_iax2.c-Avoid-crash-with-IAX2-switch-support.patch

Reported by Sergio in issue #821. This adds upstream patch for the crash. See upstream issue [1] for details.
[1] https://github.com/asterisk/asterisk/issues/180
Compile tested: sdk 22.03
Description: Patch taken from asterisk "18" branch
Closes #821

[22.03] asterisk: add upstream patch against iax2 crash

---

libs/pjproject/Makefile
net/asterisk/Makefile

Compile tested: x86 / 64 / master
Run tested: no run tests done, given the nature of the change it should be alright
Description:
Add CPE IDs for Asterisk and pjproject

Add CPE ID for asterisk and pjproject

---

net/freeswitch/Makefile
net/freeswitch/patches/500-libvpx-VP8-disallow-thread-count-changes.patch
net/freeswitch/patches/501-libvpx-Fix-bug-with-smaller-width-bigger-size.patch

Patch is for bundled libvpx, see [1].
[1] https://github.com/signalwire/freeswitch/issues/2258
Maintainer: me
Compile tested: ath79 SDK
Description:

freeswitch: add patches for CVE-2023-5217 & CVE-2023-44488 in bundled libvpx

---

net/freeswitch/Makefile
net/freeswitch/patches/500-libvpx-VP8-disallow-thread-count-changes.patch
net/freeswitch/patches/501-libvpx-Fix-bug-with-smaller-width-bigger-size.patch

CVE-2023-5217
CVE-2023-44488
Patches are for bundled libvpx, see [1].
[1] https://github.com/signalwire/freeswitch/issues/2258
(cherry picked from commit 26e09b2914af221e477a65f1ec92db48b9a9979a)
Maintainer: me
Compile tested: master
Description:

[23.05] freeswitch: add patches for CVEs in bundled libvpx

---

net/freeswitch/Makefile
net/freeswitch/patches/500-libvpx-VP8-disallow-thread-count-changes.patch
net/freeswitch/patches/501-libvpx-Fix-bug-with-smaller-width-bigger-size.patch

CVE-2023-5217
CVE-2023-44488
Patches are for bundled libvpx, see [1].
[1] https://github.com/signalwire/freeswitch/issues/2258
(cherry picked from commit 26e09b2914af221e477a65f1ec92db48b9a9979a)
Maintainer: me
Compile tested: Master
Description:

[22.03] freeswitch: add patches for CVEs in bundled libvpx

---

net/yate/Makefile
net/yate/files/banbrutes.pl

Compile tested: -
Run tested: Netgear R6220, 23.05.0-rc3
By using an nftables set in this script it's easier to install and use this script now that OpenWrt uses nftables by default.

yate: Update yate script to use an nftables set

---

net/sipgrep/Makefile
net/sipgrep/patches/001-Move-to-PCRE2-from-PCRE.patch

Add patch to convert the package to PCRE2 as PCRE is EOL and won't receive any security updates anymore.
Maintainer: Sebastian Kemper <sebastian_ml@gmx.net>

sipgrep: Move package to PCRE2

---

net/siproxd/Makefile
net/siproxd/files/siproxd.init

**Maintainer**: @micmac1 @jslachta
**Description**:
Resolve network devices by first trying `network_get_device` (L3) and falling back to `network_get_physdev` (L2) on failure, which allows using Wireguard interfaces. Both are needed to avoid breaking existing usage for some interfaces (e.g. `wan`).
Also add myself as a maintainer.
This might help or fix #800, but I can't reproduce the error myself and don't have a VOIP-over-Wireguard setup at hand.
**Testing**:
Compile tested for ipq40xx, targeting EA6350v3 device on master.
Run tested on EA6350v3 with 23.05.2.
Checked problems with `network_get_device` and `network_get_physdev` from CLI, and confirmed siproxd config file `/var/etc/siproxd/siproxd-general.conf` contains correct `wg` interface after startup with this change.

siproxd: improve network device resolution

---

net/rtpengine/Makefile

Add missing xmlrpc-c dependency.
Maintainer: Jiri + me
Description: this should fix compile issues we're having currently in master

rtpengine: bump to 11.5.1.18

---

net/rtpengine/Makefile

Fixes "RTPEngine susceptible to Denial of Service via DTLS Hello packets during call initiation", see [1].
[1] https://www.openwall.com/lists/oss-security/2023/12/15/8
Maintainer: @jslachta & me
Compile tested: sdk 22.03
Description:

[22.03] rtpengine: security bump to 9.5.8.2

---

net/pcapsipdump/patches/01-use-libc-strlcpy-if-available-v2.patch

Maintainer: nobody
Compile tested: x64 glibc toolchain built from OpenWRT commit hash eb456aedfe24a076a4f53743ad3c090ae447329e with my PR at https://github.com/openwrt/openwrt/pull/9714 applied
Description:
```
This just makes it so libbsd is picked up through pkg-config. It adds
support for libobsd without breaking libbsd.
```
This is probably my first PR to OpenWRT that isn't fixing a bug while getting what I want done so I'm pinging @neheb as an interested party.
Signed-off-by: Guilherme Janczak <guilherme.janczak@yandex.com>

pcapsipdump: fix linking against libobsd

---

libs/libsrtp/Makefile

Switch to local tarballs. Smaller.

libsrtp: update to 2.6.0

---

net/asterisk-chan-lantiq/Makefile
net/asterisk-chan-lantiq/patches/0001-handle-hook-flash-event.patch
net/asterisk-chan-lantiq/patches/0002-configure-hook-state-machine-timing.patch

Run tested: lantiq/xrx200 (arcadyan,vgv7510kw22-nor)
Description:
Import two patches which improve behavior with rotary pulse-dial phones.
Both are pending upstream:
https://github.com/kochstefan/asterisk_channel_lantiq/pull/5
https://github.com/kochstefan/asterisk_channel_lantiq/pull/6

asterisk-chan-lantiq: import patches to improve pulse-dial phones

---

net/asterisk-chan-lantiq/Makefile
net/asterisk-chan-lantiq/patches/0002-configure-hook-state-machine-timing.patch

Compile tested: mips_24kc (lantiq/xrx200)
Run tested: arcadyan,vgv7510kw22-nor (o2 Box 6431)
Description:
Apply hook state timing parameters starting from the biggest time interval down to the shortest, so the required conditions are always true while applying.

asterisk-chan-lantiq: apply hook state timing in right order

---

net/asterisk-chan-lantiq/Makefile
net/asterisk-chan-lantiq/patches/0001-handle-hook-flash-event.patch
net/asterisk-chan-lantiq/patches/0002-configure-hook-state-machine-timing.patch

Run tested: lantiq/xrx200 (arcadyan,vgv7510kw22-nor)
Description:
Backport improvements for chan_lantiq to OpenWrt 23.05

[23.05] asterisk-chan-lantiq: import patches to improve pulse-dial phones

---

net/asterisk-chan-lantiq/Makefile
net/asterisk-chan-lantiq/patches/0003-use-channel_state-enum.patch
net/asterisk-chan-lantiq/patches/0004-report-state-in-lantiq_dev_event_digit.patch
net/asterisk-chan-lantiq/patches/0005-inform-requester-about-busy-channel.patch

Compile tested: mips_24kc (lantiq/xrx200)
Run tested: arcadyan,vgv7510kw22-nor (o2 box 6431)
Description:
Import patches improving the log output of chan_lantiq.
Upstream PRs:
https://github.com/kochstefan/asterisk_channel_lantiq/pull/7
https://github.com/kochstefan/asterisk_channel_lantiq/pull/8

asterisk-chan-lantiq: import patches improving log output

---

net/baresip/Makefile
net/baresip/files/baresip.init
net/baresip/patches/010-fix-parallel-build.patch

Maintainer: @micmac1
Compile tested: mvebu, Turris Omnia, Turris OS 7 = OpenWrt 22.03
Run tested: mvebu, Turris Omnia, Turris OS 7 = OpenWrt 22.03
Description:
The build of the baresip package sometimes fails for us with the error mentioned in the commit message. After rebase to this patch everything works.

[22.03] baresip: fix init script and parallel build

---

net/yate/Makefile
net/yate/patches/100-non-gnu-mutex-type.patch

There hasn't been a yate release for years but development continues on github. Let's update the OpenWrt package to a github snapshot.
Compile tested: ramips, Netgear R6850, master + 23.05
Run tested: ramips, Netgear R6850, 23.05, SIP (registration (incoming + outgoing), call routing, calls)

yate: bump to git snapshot from 2024-09-03

---

libs/sofia-sip/Makefile

Run tested: (mips, Astoria Networks ARV7518PW,  OpenWrt 23.05.4 r24012-d8dd03c46f , sip registration and made a test sip call)
Description:
I'm trying to update my [svd package](https://github.com/olivluca/danube-voip) for OpenWrt 23.05.4. To compile it I need stun enabled. ~~I'm working on a test repository [here](https://github.com/olivluca/danube-voip-test) where~~  In my repository I adopted this version of the Makefile.

sofia-sip: removed "--disable-stun"

---

net/freeswitch/Makefile
net/freeswitch/patches/502-mod_verto-Fix-memory-leak-by-correctly-freeing-regex.patch
net/freeswitch/patches/900-Core-Move-project-to-PCRE2.patch

Add paending patch moving package to PCRE2 as PCRE is EOL and won't receive any updates anymore.
These patch were run uder the freeswitch CI and were validated with their unit tests.
Maintainer: Sebastian Kemper <sebastian_ml@gmx.net>
---
@BKPepe probably will take a bit for this to be actually merged upstream but just for reference also here...

freeswitch: add patch moving package to PCRE2

---

libs/freetdm/Makefile
libs/freetdm/patches/900-mod_freetdm-Adapt-to-new-PCRE2-API.patch

As FreeSwitch implement different API to support pcre2, freetdm require some changes to correctly compile.

freetdm: add patch for PCRE2 support

---

net/kamailio/Makefile
net/kamailio/files/kamailio.conf
net/kamailio/files/kamailio.init

bump pkg_memory 2MiB -> 3MiB.
space -> tab convert kamailio.init file
refactor kamailio.init check_listen() for clarity
cfg_target: append /
quote uci config values
chown kamailio:kamailio -R /etc/kamailio/*
debug_level 0
stderr 0

kamailio: Kamailio 6.0.1 uci config and init script fixes

---

net/baresip/Makefile
net/baresip/files/baresip.defaults
net/baresip/files/baresip.init

Adds a new UCI config section that allows the user to define accounts from which the init script will create the /etc/baresip/accounts file.
Using UCI has the big benefit, that changes in the config can be recognized by reload_config which will restart baresip automatically.
Example /etc/config/baresip:
--
config baresip main
option enable 1
option options ''
config account
option user '+49123456789'
option password ''
option server 'tel.t-online.de'
option transport 'tls'
option mediaenc 'srtp'
config account
option user '12'
option password '7282ce22eee6d91193a1d5014398356x'
option server '172.27.0.97'
option transport 'udp'
option append 'answerdelay=0;rwait=90;mwi=no'
option ignore 1
--
The basic account options user,password,server,mediaenc and tansport can be set directly. All other …

baresip: add uci config section for accounts

---

libs/dahdi-linux/Makefile
libs/dahdi-linux/patches/208-dahdi-base-fix-potential-underflow-of-unsigned-type.patch

Maintainer: @VittGam
Compile tested: mips_24kc, based on https://github.com/openwrt/openwrt/pull/18751
Run tested: -
Description:
Import pending patch to fix build with Linux 6.12
https://github.com/asterisk/dahdi-linux/pull/90

dahdi-linux: fix build with Linux 6.12
